/* ── UI FORMATTING FOR DRUGS & STEPS ── */
const S = (n,txt) => `<div class="action-step" style="display:flex; gap:10px; margin-bottom:10px; padding:15px; background:var(--bg3); border-radius:10px;"><div style="color:var(--gold); font-weight:bold;">${n}.</div><div style="color:var(--w80); font-size:14px;">${txt}</div></div>`;
const D = (name,detail) => `<div class="drug-card" style="margin-bottom:10px; padding:15px; background:var(--bg3); border-left:3px solid var(--gold); border-radius:10px;"><div style="color:var(--white); font-weight:bold; font-size:15px; margin-bottom:5px;">${name}</div><div style="color:var(--w60); font-size:13px;">${detail}</div></div>`;

/* ── DRUG REPOSITORY (RX) ── */
const RX = {
  vitk: ()=> D('Vitamin K (Phytomenadione)', LANG==='ru'?'1 мг в/м — плановая профилактика':LANG==='uz'?'1 mg IM — muntazam profilaktika':'1mg IM — routine prophylaxis'),
  dex:  ()=> D('Dextrose 50%', LANG==='ru'?'25–50 мл в/в при подтверждённой гипогликемии':LANG==='uz'?'25–50 mL IV tasdiqlangan gipoglikemiyada':'25–50 mL IV if hypoglycaemia confirmed'),
  thiamine: ()=> D('Thiamine 100mg IV/IM', LANG==='ru'?'При подозрении на алкоголизм/недоедание':LANG==='uz'?'Alkogol/oziqlanish yetishmovchiligida':' If alcohol/malnutrition suspected'),
  apix_dvt: ()=> D('Apixaban', LANG==='ru'?'10 мг 2 р/сут × 7 дней, затем 5 мг 2 р/сут × 3–6 мес':LANG==='uz'?'10 mg 2 marta/kun × 7 kun, so\'ng 5 mg 2 marta/kun × 3–6 oy':'10mg BD × 7 days, then 5mg BD × 3–6 months'),
  riva_dvt: ()=> D('Rivaroxaban', LANG==='ru'?'15 мг 2 р/сут × 21 день, затем 20 мг 1 р/сут':LANG==='uz'?'15 mg 2 marta/kun × 21 kun, so\'ng 20 mg 1 marta/kun':'15mg BD × 21 days, then 20mg OD with food'),
  apix_pe:  ()=> D('Apixaban', LANG==='ru'?'10 мг 2 р/сут × 7 дней, затем 5 мг 2 р/сут':LANG==='uz'?'10 mg 2 marta/kun × 7 kun, so\'ng 5 mg 2 marta/kun':'10mg BD × 7 days, then 5mg BD'),
  altep_pe: ()=> D('Alteplase', LANG==='ru'?'100 мг в/в за 2 ч — только при массивной ТЭЛА':LANG==='uz'?'100 mg IV 2 soatda — faqat og\'ir OE da':'100mg IV over 2h — massive PE only if haemodynamic compromise'),
  amox_curb:()=> D('Amoxicillin 500mg TDS × 5 days', LANG==='ru'?'Первая линия при ВБП':LANG==='uz'?'Birinchi qator JKP':'First-line CAP'),
  coamox:   ()=> D('IV Co-amoxiclav 1.2g TDS + Clarithromycin 500mg BD', LANG==='ru'?'Стандартная двойная в/в терапия ВБП':LANG==='uz'?'Standart IV JKP kombinatsiya':'Standard IV dual CAP therapy'),
  pip_taz:  ()=> D('Piperacillin-tazobactam 4.5g QDS', LANG==='ru'?'При риске синегнойной палочки':LANG==='uz'?'Psevdomonas xavfi bo\'lsa':'If Pseudomonas risk'),
  apix_af:  ()=> D('Apixaban 5mg BD (preferred)', LANG==='ru'?'Наименьший риск кровотечения. Снизить до 2,5 мг при ≥2 из: возраст≥80, вес≤60 кг, Кр≥133':LANG==='uz'?'Eng kam qon ketish xavfi.':'Lowest bleeding risk. Reduce to 2.5mg BD if ≥2: age≥80, wt≤60kg, Cr≥133'),
  riva_af:  ()=> D('Rivaroxaban 20mg OD with evening meal', LANG==='ru'?'Проверить СКФ — снизить до 15 мг при СКФ 15–49':LANG==='uz'?'GFR ni tekshiring — 15–49 da 15 mg':'Check eGFR — reduce to 15mg if eGFR 15–49'),
  prop:     ()=> D('Propranolol', LANG==='ru'?'20–40 мг 2 р/сут — целевая ЧСС 55–60 уд/мин':LANG==='uz'?'20–40 mg 2 marta/kun — maqsad YUR 55–60':'20–40mg BD — target HR 55–60 (if varices)'),
  spiro:    ()=> D('Spironolactone 100mg + Furosemide 40mg', LANG==='ru'?'При асците — подбирать по диурезу':LANG==='uz'?'Assit uchun — diurezga qarab sozlash':'Titrate to diuresis (ascites)'),
  lact:     ()=> D('Lactulose 15–30mL BD', LANG==='ru'?'Цель: 2–3 мягких стула/сут (энцефалопатия)':LANG==='uz'?'Maqsad: 2–3 yumshoq najasot/kun (ensefalopati)':'Target 2–3 soft stools/day — encephalopathy'),
  norflo:   ()=> D('Norfloxacin 400mg OD', LANG==='ru'?'Профилактика СБП при белке асцитической жидкости < 15 г/л':LANG==='uz'?'Assit oqsili < 15 g/L da SBP profilaktikasi':'SBP prophylaxis if ascites protein < 15g/L'),
  terlip:   ()=> D('Terlipressin 0.5–2mg IV QDS + Albumin', LANG==='ru'?'Гепаторенальный синдром':LANG==='uz'?'Gepatorental sindrom':'Hepatorenal syndrome'),
  hicalnor: ()=> D('High-calorie supplements', LANG==='ru'?'Ensure/Fortisip 2–3 шт/сут':LANG==='uz'?'Ensure/Fortisip kuniga 2–3 ta':'Ensure/Fortisip 2–3/day'),
  sema:     ()=> D('Semaglutide 2.4mg SC weekly (Wegovy)', LANG==='ru'?'ГПП-1 — снижение веса в среднем 12–15%':LANG==='uz'?'GLP-1 — o\'rtacha 12–15% vazn yo\'qotish':'GLP-1 agonist — average 12–15% weight loss'),
  orli:     ()=> D('Orlistat 120mg TDS', LANG==='ru'?'Более старый препарат — умеренный эффект':LANG==='uz'?'Eski dori — o\'rtacha effekt':'Older agent — modest effect'),
  bariatric:()=> D('Bariatric surgery assessment', LANG==='ru'?'При недостаточности фармакотерапии':LANG==='uz'?'Farmakoterapiya yetarli bo\'lmasa':'If pharmacotherapy insufficient'),
  acei:     ()=> D('ACEi or ARB', LANG==='ru'?'Нефропротекция при протеинурии':LANG==='uz'?'Proteinuriyada nefroprotektsiya':'Nephroprotection with proteinuria'),
  sglt2:    ()=> D('Dapagliflozin 10mg OD', LANG==='ru'?'Нефропротекция независимо от СД':LANG==='uz'?'QD dan qat\'iy nazar nefroprotektsiya':'CKD-protective regardless of DM'),
  esa:      ()=> D('ESA if Hb < 100 + iron replete', LANG==='ru'?'Обсудить с нефрологом':LANG==='uz'?'Nefrolog bilan muhokama qiling':'Discuss with nephrology'),
  iv_fluid: ()=> D('IV crystalloid (0.9% NaCl or Hartmann\'s)', LANG==='ru'?'250–500 мл болюс, переоценка ответа':LANG==='uz'?'250–500 mL bolus, javobni qayta baholang':'250–500 mL boluses, reassess response'),
  nora:     ()=> D('Noradrenaline', LANG==='ru'?'0,01–3 мкг/кг/мин — целевое СрАД ≥ 65':LANG==='uz'?'0,01–3 mkg/kg/daqiqa — maqsad MAP ≥ 65':'0.01–3 mcg/kg/min — titrate MAP ≥ 65'),
  hc:       ()=> D('Hydrocortisone 200mg/day', LANG==='ru'?'50 мг 4 р/сут в/в при рефрактерном шоке':LANG==='uz'?'Refrakter shokda 50 mg 4 marta/kun IV':'50mg QDS IV if refractory shock'),
  vaso:     ()=> D('Vasopressin 0.03 units/min', LANG==='ru'?'Дополнение к норадреналину — снижает потребность':LANG==='uz'?'Noradrenalinga qo\'shimcha — miqdorini kamaytiradi':'Adjunct to noradrenaline — reduces requirements'),
  crrt:     ()=> D('CRRT', LANG==='ru'?'Предпочтительно при гемодинамической нестабильности':LANG==='uz'?'Gemodinamik beqarorlikda afzal':'Preferred over intermittent HD if haemodynamically unstable'),
  penV:     ()=> D('Phenoxymethylpenicillin 500mg BD × 10 days', LANG==='ru'?'Первая линия — 10 дней лучше 5':LANG==='uz'?'Birinchi qator — 10 kun 5 kundan yaxshiroq':'First-line — superior to 5-day course'),
  clari_strep: ()=> D('Clarithromycin 250mg BD × 5 days', LANG==='ru'?'При аллергии на пенициллин':LANG==='uz'?'Penitsillin allergiyasida':'If penicillin allergy'),
  aspirin_tia: ()=> D('Aspirin 300mg stat', LANG==='ru'?'После исключения геморрагии по КТ':LANG==='uz'?'KT da gemorragiya istisno qilingandan so\'ng':'After excluding haemorrhage on CT'),
  thrombect: ()=> D('Mechanical Thrombectomy', LANG==='ru'?'При ОЛО — до 24 ч при наличии жизнеспособной ткани':LANG==='uz'?'OBO bo\'lsa — tirik to\'qima bo\'lsa 24 soatgacha':'If LVO on CTA — up to 24h with salvageable tissue'),
  altep_str: ()=> D('Alteplase 0.9 mg/kg IV', LANG==='ru'?'10% болюс, остаток за 60 мин — при давности ≤ 4,5 ч':LANG==='uz'?'10% bolus, 60 daqiqada qolgani — ≤ 4,5 soat':'10% bolus, remainder over 60 min — if ≤4.5h'),
  leve:     ()=> D('Levetiracetam 500mg BD', LANG==='ru'?'При судорогах':LANG==='uz'?'Tutqanoq bo\'lsa':'If seizures'),
  pip_sep:  ()=> D('Piperacillin-tazobactam 4.5g IV QDS', LANG==='ru'?'При подозрении на сепсис':LANG==='uz'?'Sepsis shubhali bo\'lsa':'Broad-spectrum if sepsis'),
  nnj:      ()=> D('Nasojejunal feeding', LANG==='ru'?'Защищает кишечный барьер':LANG==='uz'?'Ichak to\'sig\'ini himoya qiladi':'Protects gut barrier, reduces infectious complications'),
  mero:     ()=> D('Meropenem 1g TDS', LANG==='ru'?'Только при подтверждённом инфицированном некрозе':LANG==='uz'?'Faqat tasdiqlangan infitsiyalangan nekrozda':'Only if confirmed infected necrosis — NOT routine prophylaxis'),
  pn:       ()=> D('Parenteral nutrition via CVC', LANG==='ru'?'Если энтеральный путь невозможен':LANG==='uz'?'Enteral yo\'l mumkin bo\'lmasa':'If enteral route impossible'),
  ketam:    ()=> D('Ketamine (RSI induction) 1–2mg/kg IV', LANG==='ru'?'Предпочтителен при нестабильности':LANG==='uz'?'Gemodinamik beqarorlikda afzal':'Preferred in haemodynamic instability'),
  suxam:    ()=> D('Suxamethonium (RSI paralytic) 1.5mg/kg IV', LANG==='ru'?'Для быстрой интубации':LANG==='uz'?'Tez intubatsiya uchun':'For Rapid Sequence Intubation'),
  manni:    ()=> D('Mannitol 20% 0.5–1g/kg IV', LANG==='ru'?'При подозрении на повышение ВЧД':LANG==='uz'?'IKB shubhali bo\'lsa':'If raised ICP — discuss with neurosurgery'),
  leve2:    ()=> D('Levetiracetam 500mg IV', LANG==='ru'?'Профилактика судорог':LANG==='uz'?'Tutqanoq profilaktikasi':'If seizure prophylaxis needed'),
  adren_ap: ()=> D('Adrenaline 0.01–0.03mg/kg IV', LANG==='ru'?'Реанимация новорождённых':LANG==='uz'?'Yangi tug\'ilgan reanimatsiyasi':'Neonatal resuscitation'),
  bicarb:   ()=> D('Sodium Bicarbonate 4.2% 1–2mmol/kg', LANG==='ru'?'Только при остановке сердца с ацидозом':LANG==='uz'?'Faqat tutqanoqda atsidoz bo\'lsa':'Only if prolonged arrest with acidosis'),
  o2:       ()=> D('O₂ 100% via face mask', LANG==='ru'?'Подбирать по сатурации':LANG==='uz'?'Saturatsiyaga qarab sozlash':'Titrate to saturations'),
  glucose10:()=> D('Glucose 10% 2mL/kg IV', LANG==='ru'?'При гипогликемии':LANG==='uz'?'Gipoglikemiyada':'If hypoglycaemia'),
  hart:     ()=> D("Hartmann's solution", LANG==='ru'?'250–500 мл/ч в течение 24–48 ч':LANG==='uz'?'250–500 mL/soat 24–48 soat':'250–500mL/hr for 24–48h'),
  morph:    ()=> D("Morphine 2.5–5mg IV PRN", LANG==='ru'?'Обезболивание — безопасно':LANG==='uz'?'Og\'riq qoldirish — xavfsiz':'Analgesia — safe to use in pancreatitis'),
  noab:     ()=> D('No antibiotics required', LANG==='ru'?'Ненужные антибиотики способствуют резистентности':LANG==='uz'?'Antibiotik kerak emas':'Viral etiology most likely'),
  paracib:  ()=> D('Paracetamol 1g QDS + Ibuprofen 400mg TDS', LANG==='ru'?'Чередование обеспечивает лучший эффект':LANG==='uz'?'Navbatma-navbat berish yaxshiroq':'Alternating provides superior pain relief'),
  stopmeta: ()=> D('Stop Metformin', LANG==='ru'?'Риск лактацидоза при СКФ < 30':LANG==='uz'?'GFR < 30 da laktatsidoz xavfi':'Risk of lactic acidosis below eGFR 30'),
  phosbind: ()=> D('Phosphate binders', LANG==='ru'?'С едой':LANG==='uz'?'Ovqat bilan':'With meals'),
  alfacal:  ()=> D('Alfacalcidol', LANG==='ru'?'При повышении ПТГ':LANG==='uz'?'PTH ko\'tarilganda':'If PTH elevated'),
  enox:     ()=> D('Enoxaparin 1mg/kg SC BD', LANG==='ru'?'Мост-терапия при ожидании визуализации':LANG==='uz'?'Tasvirlash kutilayotganda ko\'prik terapiya':'LMWH bridge while awaiting imaging'),
  coamoxlev: ()=> D('IV Co-amoxiclav 1.2g TDS + Clarithromycin 500mg BD', LANG==='ru'?'Немедленная двойная терапия':LANG==='uz'?'Darhol ikki tomonlama terapiya':'Immediate dual IV CAP therapy'),
  levo_psi: ()=> D('Levofloxacin 500mg BD', LANG==='ru'?'При аллергии на пенициллин':LANG==='uz'?'Penitsillin allergiyasida':'If penicillin allergy'),
  aspirin_af: ()=> D('Aspirin NOT recommended in AF', LANG==='ru'?'Для профилактики инсульта не применяется':LANG==='uz'?'Insult profilaktikasi uchun emas':'Not effective for stroke prevention in AF'),
};
