'use strict';

/**
 * WARDCALC MASTER DICTIONARY
 * Developer: Muhammad Sabir Ali, Final year student at Bukhara State Medical Institute.
 * Contains 100% of UI, Questions, Toggles, Full NIHSS, and Expert Clinical Triage Guidelines.
 */

window.T = {
en:{
  hero_desc: '15 evidence-based calculators with mnemonics in 3 languages. Fast, reliable, and mobile-first — everything you need at the bedside.',
  stat_calc: 'Calculators',
  stat_lang: 'Languages',
  stat_free: 'Free',
  all_label: 'All Calculators',

  badge: 'CLINICAL DECISION TOOLS', h1a: 'Ward', h1b: 'Calc', sub: 'Evidence-based medical calculators.', badge_stu: 'BUILT BY A MEDICAL STUDENT · FOR MEDICAL PROFESSIONALS', h1_main: 'Clinical Tools', h1_sub: 'for Ward Rounds', search_ph: 'Search tools (e.g., GCS, BMI)...', alert_msg: 'Please complete all required fields.', btn: 'Calculate', tab_i: 'Interpretation', tab_a: 'Action Plan', tab_d: 'First-Line Rx', yes: 'Yes', no: 'No', YES: 'Yes', NO: 'No', mnem_all: 'Memory Aid / Mnemonics', MNEM_ALL: 'Memory Aid / Mnemonics',
  sp_neuro: 'Neurology', sp_ped: 'Pediatrics', sp_gen: 'General', sp_resp: 'Respiratory', sp_cardio: 'Cardiology', sp_gastro: 'Gastroenterology', sp_id: 'Infectious Disease', sev_lo: 'LOW RISK', sev_md: 'MODERATE RISK', sev_hi: 'HIGH RISK', 
  ft_about: 'About Us', ft_contact: 'Contact', ft_disc: 'Disclaimer', ft_terms: 'Terms', ft_privacy: 'Privacy', ft_rights: '© 2026 WardCalc. All rights reserved.',
  nav_about: 'About WardCalc', about_p1: 'WardCalc is a comprehensive clinical decision support system developed by Muhammad Sabir Ali, Final year student at Bukhara State Medical Institute.', about_h2: 'Our Mission', about_p2: 'In acute medical settings, time and accuracy are paramount. Our mission is to digitize internationally validated medical scoring systems into a mobile-first interface.', about_h3: 'Educational Purpose', about_p3: 'Designated as an educational tool to assist, not replace, formal clinical judgment.',
  nav_contact: 'Contact & Support', contact_p1: 'We are committed to continuous clinical and technical improvement.', contact_p2: 'Please submit an issue via our official GitHub repository.',
  nav_disc: 'Clinical Disclaimer', disc_p1: 'Strictly for educational and informational purposes. Do not constitute definitive medical advice.', disc_p2: 'Muhammad Sabir Ali assumes no liability for clinical decisions made based on this application.',
  nav_terms: 'Terms of Use', terms_p1: 'Application is provided "as is" without implied warranties.', terms_p2: 'Users are responsible for verifying accuracy.',
  nav_privacy: 'Privacy Policy', privacy_p1: 'WardCalc operates entirely client-side locally within your browser.', privacy_p2: 'We do not collect, transmit, or store patient data.',

  // QUESTIONS & FACTORS
  f_eye:'Eye Opening', f_verbal:'Verbal Response', f_motor:'Motor Response', g_e4:'Spontaneous (4)', g_e3:'To voice (3)', g_e2:'To pain (2)', g_e1:'None (1)', g_v5:'Oriented (5)', g_v4:'Confused (4)', g_v3:'Words (3)', g_v2:'Sounds (2)', g_v1:'None (1)', g_m6:'Obeys (6)', g_m5:'Localizes (5)', g_m4:'Withdrawal (4)', g_m3:'Flexion (3)', g_m2:'Extension (2)', g_m1:'None (1)',
  f_appear:'Appearance', f_pulse:'Pulse', f_grimace:'Grimace', f_activity:'Activity', f_resp_a:'Respiration', a_a2:'Pink (2)', a_a1:'Blue ext. (1)', a_a0:'Pale (0)', a_p2:'≥ 100 (2)', a_p1:'< 100 (1)', a_p0:'Absent (0)', a_g2:'Cry (2)', a_g1:'Grimace (1)', a_g0:'None (0)', a_c2:'Active (2)', a_c1:'Flexion (1)', a_c0:'Limp (0)', a_r2:'Strong (2)', a_r1:'Weak (1)', a_r0:'Absent (0)',
  f_cancer:'Active cancer', d1:'Active cancer', f_paralysis:'Paralysis', d2:'Paralysis', f_bedridden:'Bedridden > 3 days', d3:'Bedridden > 3 days', f_tenderness:'Localized tenderness', d4:'Localized tenderness', f_swelling_entire:'Entire leg swollen', d5:'Entire leg swollen', f_swelling_calf:'Calf swelling > 3 cm', d6:'Calf swelling > 3 cm', f_pitting:'Pitting edema', d7:'Pitting edema', f_collateral:'Collateral veins', d8:'Collateral veins', f_alt_dx:'Alt diagnosis likely (-2)', d9:'Alt diagnosis likely (-2)',
  f_pe_dvt:'Signs of DVT', p1:'Signs of DVT', f_pe_alt:'Alt diagnosis unlikely', p2:'Alt diagnosis unlikely', f_pe_hr:'Heart rate > 100', p3:'Heart rate > 100', f_pe_immob:'Immobilization', p4:'Immobilization', f_pe_hx:'Previous PE/DVT', p5:'Previous PE/DVT', f_pe_hemop:'Hemoptysis', p6:'Hemoptysis', f_pe_malig:'Malignancy', p7:'Malignancy',
  f_confusion:'Confusion', c1:'Confusion', f_urea:'BUN > 19', c2:'BUN > 19', f_rr30:'Resp Rate ≥ 30', c3:'Resp Rate ≥ 30', f_bp_low:'BP < 90/60', c4:'BP < 90/60', f_age65:'Age ≥ 65', c5:'Age ≥ 65',
  ch_c:'C: Heart Failure (+1)', ch_h:'H: Hypertension (+1)', ch_a2:'A: Age ≥ 75 (+2)', ch_d:'D: Diabetes (+1)', ch_s2:'S: Stroke/TIA (+2)', ch_v:'V: Vascular Disease (+1)', ch_a1:'A: Age 65-74 (+1)', ch_sex:'S: Female Sex (+1)',
  f_bili:'Bilirubin', f_alb:'Albumin', f_pt:'PT / INR', f_ascites:'Ascites', f_enceph:'Encephalopathy', cp_b1:'< 34', cp_b2:'34–50', cp_b3:'> 50', cp_a1:'> 35', cp_a2:'28–35', cp_a3:'< 28', cp_p1:'< 1.7', cp_p2:'1.7–2.3', cp_p3:'> 2.3', cp_as2:'Mild/Mod', cp_as3:'Severe', cp_e2:'Grade I–II', cp_e3:'Grade III–IV',
  f_weight:'Weight (kg)', f_height:'Height (cm)', f_cr:'Creatinine', f_age:'Age', f_sex:'Sex', sex_m:'Male', sex_f:'Female',
  f_mews_rr:'Resp Rate', f_mews_hr:'Heart Rate', f_mews_sbp:'Systolic BP', f_mews_temp:'Temperature', f_mews_avpu:'Consciousness',
  f_cough_a:'No cough', f_exudates:'Exudates', f_lymph:'Tender lymph nodes', f_temp38:'Temp > 38.0°C', f_c_age:'Age Group', c_age_1:'3-14 (+1)', c_age_2:'15-44 (0)', c_age_3:'≥ 45 (-1)',
  f_pao2:'PaO2/FiO2', f_plt:'Platelets', f_bili_sofa:'Bilirubin', f_map:'MAP / Vasopressors', f_gcs_sofa:'GCS Score', f_cr_sofa:'Creatinine',
  f_age55:'Age > 55', f_wbc:'WBC > 16k', f_glu:'Glucose > 200', f_ldh:'LDH > 350', f_ast:'AST > 250', f_hct_drop:'Hct drop > 10%', f_bun_rise:'BUN rise', f_ca_low:'Ca < 8', f_pao2_low:'PaO2 < 60', f_base_def:'Base deficit > 4', f_fluid_seq:'Fluid > 6L',
  f_psi_age:'Age', psi_age:'Age', f_psi_sex:'Sex', psi_sex:'Sex', f_psi_nh:'Nursing home', psi_nh:'Nursing home', f_psi_neo:'Neoplasm', psi_neo:'Neoplasm', f_psi_liv:'Liver disease', psi_liv:'Liver disease', f_psi_chf:'Heart Failure', psi_chf:'Heart Failure', f_psi_cvd:'Stroke', psi_cvd:'Stroke', f_psi_ren:'Renal disease', psi_ren:'Renal disease', f_psi_ams:'Altered mental status', psi_ams:'Altered mental status', f_psi_rr:'RR ≥ 30', psi_rr:'RR ≥ 30', f_psi_sbp:'SBP < 90', psi_sbp:'SBP < 90', f_psi_temp:'Temp < 35 or ≥ 40', psi_temp:'Temp < 35 or ≥ 40', f_psi_pulse:'Pulse ≥ 125', psi_pulse:'Pulse ≥ 125', f_psi_ph:'pH < 7.35', psi_ph:'pH < 7.35', f_psi_bun:'BUN ≥ 30', psi_bun:'BUN ≥ 30', f_psi_na:'Na < 130', psi_na:'Na < 130', f_psi_gluc:'Gluc ≥ 250', psi_gluc:'Gluc ≥ 250', f_psi_hct:'Hct < 30%', psi_hct:'Hct < 30%', f_psi_pao2:'PaO2 < 60', psi_pao2:'PaO2 < 60', f_psi_eff:'Effusion', psi_eff:'Effusion',
  
  // NEW NIHSS FULL QUESTIONS
  n1a_q:'1a. Level of Consciousness', n1a_0:'0: Alert', n1a_1:'1: Arousable', n1a_2:'2: Obtunded', n1a_3:'3: Coma',
  n1b_q:'1b. LOC Questions (Month/Age)', n1b_0:'0: Answers both', n1b_1:'1: Answers one', n1b_2:'2: Answers neither',
  n1c_q:'1c. LOC Commands (Open eyes, grip)', n1c_0:'0: Performs both', n1c_1:'1: Performs one', n1c_2:'2: Performs neither',
  n2_q:'2. Best Gaze', n2_0:'0: Normal', n2_1:'1: Partial gaze palsy', n2_2:'2: Forced deviation',
  n3_q:'3. Visual Fields', n3_0:'0: No visual loss', n3_1:'1: Partial hemianopia', n3_2:'2: Complete hemianopia', n3_3:'3: Bilateral hemianopia',
  n4_q:'4. Facial Palsy', n4_0:'0: Normal', n4_1:'1: Minor paralysis', n4_2:'2: Partial paralysis', n4_3:'3: Complete paralysis',
  n5a_q:'5a. Motor Left Arm', n5a_0:'0: No drift', n5a_1:'1: Drift', n5a_2:'2: Can\'t resist gravity', n5a_3:'3: No gravity resistance', n5a_4:'4: No movement',
  n5b_q:'5b. Motor Right Arm', n5b_0:'0: No drift', n5b_1:'1: Drift', n5b_2:'2: Can\'t resist gravity', n5b_3:'3: No gravity resistance', n5b_4:'4: No movement',
  n6a_q:'6a. Motor Left Leg', n6a_0:'0: No drift', n6a_1:'1: Drift', n6a_2:'2: Can\'t resist gravity', n6a_3:'3: No gravity resistance', n6a_4:'4: No movement',
  n6b_q:'6b. Motor Right Leg', n6b_0:'0: No drift', n6b_1:'1: Drift', n6b_2:'2: Can\'t resist gravity', n6b_3:'3: No gravity resistance', n6b_4:'4: No movement',
  n7_q:'7. Limb Ataxia', n7_0:'0: Absent', n7_1:'1: Present in 1 limb', n7_2:'2: Present in 2 limbs',
  n8_q:'8. Sensory', n8_0:'0: Normal', n8_1:'1: Mild-to-moderate loss', n8_2:'2: Severe-to-total loss',
  n9_q:'9. Best Language', n9_0:'0: No aphasia', n9_1:'1: Mild-to-moderate', n9_2:'2: Severe aphasia', n9_3:'3: Mute/Global',
  n10_q:'10. Dysarthria', n10_0:'0: Normal', n10_1:'1: Mild-to-moderate', n10_2:'2: Severe/Mute',
  n11_q:'11. Extinction/Inattention', n11_0:'0: Normal', n11_1:'1: Mild inattention', n11_2:'2: Profound hemi-inattention',

  // --- EXPERT CLINICAL TEXT ---
  d_gcs: 'Assess consciousness level. The baseline score demanded on every trauma call.', r_gcs_mi: 'Mild Head Injury (GCS 13-15).', a_gcs_mi: '• Conduct full neurological exam.<br>• Routine neuro-obs every 30-60 mins.', rx_gcs_mi_n: 'Supportive Care', rx_gcs_mi_d: 'Analgesia (e.g., Paracetamol). Avoid sedating opioids.', r_gcs_mo: 'Moderate TBI (GCS 9-12). High risk for secondary brain ischemia.', a_gcs_mo: '• Urgent non-contrast CT head.<br>• Immediate Neurosurgery consultation.<br>• Elevate head of bed to 30°.', rx_gcs_mo_n: 'Neuroprotection', rx_gcs_mo_d: 'Consider prophylactic Levetiracetam (500mg IV BID).', r_gcs_se: 'Severe TBI (GCS ≤ 8). Inability to protect airway independently.', a_gcs_se: '• IMMEDIATE airway protection (RSI).<br>• Urgent non-contrast CT head & C-spine.<br>• Admit directly to Neuro-ICU.', rx_gcs_se_n: 'ICP Management', rx_gcs_se_d: 'Propofol/Ketamine. If herniating: Mannitol 20% or Hypertonic Saline.', gcs_info_title: 'Evidence & Insights: GCS', gcs_info_p1: 'Overview: Developed in 1974 by Teasdale and Jennett, the Glasgow Coma Scale standardizes the assessment of consciousness in acute brain injury and systemic illness.', gcs_info_p2: 'Clinical Pearls: The motor score is the most reliable independent predictor of prognosis. If responses are asymmetrical (e.g., due to hemiparesis), always score the BEST responding side. If eyes cannot open due to orbital edema, record as "NT" (Not Testable).', gcs_info_p3: 'Next Steps: A GCS of 8 or less defines a coma. It indicates the patient\'s inability to independently protect their airway, serving as an absolute threshold for emergent endotracheal intubation.',
  d_apgar: 'Newborn assessment at 1 and 5 minutes.', r_apgar_no: 'Normal Neonatal Transition.', a_apgar_no: '• Provide routine postnatal care.<br>• Promote immediate skin-to-skin contact.', rx_apgar_no_n: 'Routine Prophylaxis', rx_apgar_no_d: 'IM Vitamin K 1mg. Erythromycin eye ointment.', r_apgar_mo: 'Moderately Depressed.', a_apgar_mo: '• Provide vigorous tactile stimulation.<br>• Administer blow-by oxygen or CPAP.', rx_apgar_mo_n: 'Oxygen Therapy', rx_apgar_mo_d: 'Titrate FiO2 to maintain targeted SpO2 percentiles.', r_apgar_cr: 'Critically Low.', a_apgar_cr: '• Initiate Neonatal Resuscitation Protocol (NRP).<br>• Start Positive Pressure Ventilation (PPV).', rx_apgar_cr_n: 'Resuscitation Drugs', rx_apgar_cr_d: 'If HR < 60 after PPV/compressions, administer IV Epinephrine (0.01-0.03 mg/kg).', apgar_info_title: 'Evidence & Insights: APGAR', apgar_info_p1: 'Overview: Devised by Dr. Virginia Apgar in 1952. The 1-minute score reflects labor tolerance; the 5-minute score assesses extrauterine adaptation.', apgar_info_p2: 'Clinical Pearls: Heart rate and respiratory effort are paramount for survival, while skin color (acrocyanosis) is the least reliable metric.', apgar_info_p3: 'Guidelines: ACOG emphasizes that APGAR alone should NOT diagnose asphyxia. A score <7 at 5 mins mandates scoring every 5 mins (up to 20 mins) and active resuscitation.',
  d_dvt: 'Estimate the pre-test probability of DVT.', r_dvt_lo: 'DVT Unlikely.', a_dvt_lo: '• Perform high-sensitivity D-Dimer test.<br>• If negative, DVT safely excluded.', rx_dvt_lo_n: 'No Anticoagulation', rx_dvt_lo_d: 'Do not initiate empiric therapeutic anticoagulation.', r_dvt_md: 'Moderate Probability.', a_dvt_md: '• Obtain D-Dimer testing.<br>• If positive, proceed to proximal vein ultrasound.', rx_dvt_md_n: 'Hold Therapy', rx_dvt_md_d: 'Hold empiric therapy unless ultrasound delayed > 4 hours.', r_dvt_hi: 'DVT Likely.', a_dvt_hi: '• Proceed directly to venous ultrasound.<br>• Assess patient bleeding risk.', rx_dvt_hi_n: 'Empiric Anticoagulation', rx_dvt_hi_d: 'If scan delayed, start DOAC (Apixaban/Rivaroxaban) or LMWH.', dvt_info_title: 'Evidence & Insights: Wells DVT', dvt_info_p1: 'Overview: A validated prediction rule designed to estimate DVT probability before initiating costly imaging or hazardous anticoagulation.', dvt_info_p2: 'Clinical Pearls: "Alternative diagnosis at least as likely" requires strong clinical gestalt. Consider cellulitis, ruptured Baker’s cyst, or heart failure.', dvt_info_p3: 'Next Steps: In low-risk patients, a negative high-sensitivity D-dimer safely rules out DVT. In high-risk patients (≥2), D-dimer is insufficient; proceed to ultrasonography.',
  d_pe: 'Calculate pre-test probability to guide PE imaging.', r_pe_lo: 'PE Unlikely.', a_pe_lo: '• Apply PERC rule or obtain D-Dimer.', rx_pe_lo_n: 'No Anticoagulation', rx_pe_lo_d: 'Empiric anticoagulation is contraindicated.', r_pe_md: 'Moderate Risk.', a_pe_md: '• Obtain high-sensitivity D-Dimer.<br>• If positive, proceed to CTPA imaging.', rx_pe_md_n: 'Hold Anticoagulation', rx_pe_md_d: 'Wait for CTPA results unless imaging is delayed.', r_pe_hi: 'PE Likely.', a_pe_hi: '• Proceed directly to CTPA.<br>• D-Dimer testing is not appropriate.', rx_pe_hi_n: 'Therapeutic Anticoagulation', rx_pe_hi_d: 'Start immediately (LMWH or IV Heparin) pending scan.', pe_info_title: 'Evidence & Insights: Wells PE', pe_info_p1: 'Overview: Stratifies PE risk to prevent unnecessary CT Pulmonary Angiography (CTPA) and its associated radiation/contrast nephropathy risks.', pe_info_p2: 'Clinical Pearls: Tachycardia (>100 bpm) is a strong but nonspecific predictor. Suspect PE in unexplained hypoxia, pleuritic pain, or S1Q3T3 on ECG.', pe_info_p3: 'Next Steps: If PE is "Likely" (>4), do NOT order a D-Dimer; it cannot safely rule out PE. Proceed immediately to CTPA.',
  d_curb65: 'Mortality risk stratification for CAP.', r_curb_lo: 'Low mortality risk (< 2%).', a_curb_lo: '• Suitable for outpatient management.<br>• Provide strict safety-netting advice.', rx_curb_lo_n: 'Outpatient Antimicrobials', rx_curb_lo_d: 'Amoxicillin 500mg TDS or Doxycycline 100mg BID for 5-7 days.', r_curb_md: 'Moderate mortality risk (~9%).', a_curb_md: '• Hospital admission to general medical ward.<br>• Obtain blood cultures and sputum Gram stain.', rx_curb_md_n: 'Inpatient Antimicrobials', rx_curb_md_d: 'IV Amoxicillin/Clavulanate (1.2g TDS) + Oral Clarithromycin.', r_curb_hi: 'Severe CAP (Mortality > 22%).', a_curb_hi: '• Mandatory hospitalization; evaluate for ICU.<br>• ABG analysis; prepare for mechanical ventilation.', rx_curb_hi_n: 'ICU Broad-Spectrum ABX', rx_curb_hi_d: 'IV Ceftriaxone (2g OD) PLUS IV Macrolide. Add MRSA coverage if indicated.', curb_info_title: 'Evidence & Insights: CURB-65', curb_info_p1: 'Overview: Endorsed by the British Thoracic Society (BTS) to accurately predict 30-day mortality in Community-Acquired Pneumonia (CAP).', curb_info_p2: 'Clinical Pearls: Urea > 7 mmol/L reflects dehydration and poor renal perfusion secondary to sepsis. "Confusion" means an AMTS ≤ 8.', curb_info_p3: 'Next Steps: Score 0-1 implies safe outpatient treatment. Score 2 mandates ward admission. Score 3+ implies severe CAP with up to 40% mortality.',
  d_chads2: 'Stroke risk stratification in atrial fibrillation.', r_chads_lo: 'Low Stroke Risk.', a_chads_lo: '• Evaluate individual bleeding risks (HAS-BLED).<br>• Focus on lifestyle modifications.', rx_chads_lo_n: 'No Anticoagulation', rx_chads_lo_d: 'Antithrombotic therapy is generally not recommended.', r_chads_md: 'Intermediate Stroke Risk.', a_chads_md: '• Consider patient preferences and bleeding risk.<br>• Shared decision-making regarding therapy.', rx_chads_md_n: 'Consider DOAC', rx_chads_md_d: 'Oral anticoagulation considered based on individual benefit-risk profile.', r_chads_hi: 'High Stroke Risk.', a_chads_hi: '• Strong clinical indication for systemic anticoagulation.<br>• Ensure strict medication compliance.', rx_chads_hi_n: 'Lifelong Anticoagulation', rx_chads_hi_d: 'DOACs preferred (e.g., Apixaban 5mg BID) over Warfarin unless contraindicated.', chads_info_title: 'Evidence & Insights: CHA₂DS₂-VASc', chads_info_p1: 'Overview: The AHA/ACC/ESC recommended scoring system to estimate annual risk of ischemic stroke in non-valvular Atrial Fibrillation.', chads_info_p2: 'Clinical Pearls: "Non-valvular" means the absence of moderate-to-severe mitral stenosis or a mechanical heart valve. Calculate HAS-BLED concurrently.', chads_info_p3: 'Guidelines: A score of ≥2 in men or ≥3 in women represents a definitive indication for lifelong oral anticoagulation, with DOACs favored over Warfarin.',
  d_cp: 'Prognostic classification of liver cirrhosis.', r_cp_a: 'Class A: Compensated Cirrhosis.', a_cp_a: '• Routine hepatology follow-up.<br>• Screen for esophageal varices via endoscopy.', rx_cp_a_n: 'Standard Care', rx_cp_a_d: 'Avoid hepatotoxic medications. Vaccinate for Hep A and B.', r_cp_b: 'Class B: Significant Impairment.', a_cp_b: '• Formal hepatology evaluation.<br>• Increased perioperative mortality risk.', rx_cp_b_n: 'Targeted Management', rx_cp_b_d: 'Non-selective beta-blockers (Propranolol) for portal hypertension.', r_cp_c: 'Class C: Decompensated Cirrhosis.', a_cp_c: '• Urgent transplant evaluation required.<br>• Monitor closely for spontaneous bacterial peritonitis (SBP).', rx_cp_c_n: 'Complication Management', rx_cp_c_d: 'Spironolactone/Furosemide for ascites. Lactulose for encephalopathy.', cp_info_title: 'Evidence & Insights: Child-Pugh', cp_info_p1: 'Overview: A classic prognostic model used to estimate 1- and 2-year survival in patients with cirrhosis, and evaluate perioperative risk.', cp_info_p2: 'Clinical Pearls: Subjective criteria (ascites and encephalopathy) can be artificially altered by recent medical interventions (e.g., diuresis).', cp_info_p3: 'Next Steps: Class A boasts a ~100% 1-year survival. Class C indicates end-stage decompensation with only ~45% 1-year survival, mandating immediate transplant evaluation.',
  d_bmi: 'Body Mass Index calculation.', r_bmi_un: 'Underweight (BMI < 18.5).', a_bmi_un: '• Assess for malnutrition or eating disorders.<br>• Rule out hyperthyroidism or malignancy.', rx_bmi_un_n: 'Nutritional Support', rx_bmi_un_d: 'High-caloric dietary supplementation.', r_bmi_no: 'Normal Weight (18.5 - 24.9).', a_bmi_no: '• Encourage maintenance of healthy lifestyle.<br>• Routine annual cardiovascular screening.', rx_bmi_no_n: 'Preventative Care', rx_bmi_no_d: 'No pharmacological intervention indicated.', r_bmi_ov: 'Overweight (25 - 29.9).', a_bmi_ov: '• Recommend 5-10% weight loss.<br>• Screen for metabolic syndrome.', rx_bmi_ov_n: 'Lifestyle Optimization', rx_bmi_ov_d: 'Dietary caloric restriction. Meds rarely indicated.', r_bmi_ob1: 'Obesity Class I (30 - 34.9).', a_bmi_ob1: '• Intensive multidisciplinary lifestyle intervention.<br>• Aggressive management of comorbidities.', rx_bmi_ob1_n: 'Consider Pharmacotherapy', rx_bmi_ob1_d: 'GLP-1 receptor agonists (e.g., Semaglutide) if lifestyle fails.', r_bmi_ob2: 'Severe Obesity (BMI ≥ 35).', a_bmi_ob2: '• High risk for severe cardiovascular events.<br>• Screen for Obstructive Sleep Apnea (OSA).', rx_bmi_ob2_n: 'Aggressive Intervention', rx_bmi_ob2_d: 'Maximally tolerate medical therapy; prepare for surgical options.', bmi_info_title: 'Evidence & Insights: BMI', bmi_info_p1: 'Overview: The World Health Organization (WHO) standard for anthropometric tracking, providing a baseline metric for cardiovascular and metabolic risk stratification.', bmi_info_p2: 'Clinical Pearls: BMI does not differentiate between muscle mass and adipose tissue, potentially misclassifying bodybuilders. Conversely, it may fail to identify dangerous visceral adiposity in "normal-weight obesity".', bmi_info_p3: 'Next Steps: Note that Asian populations exhibit higher cardiometabolic risks at lower BMIs; WHO guidelines adjust "Overweight" to ≥23 and "Obesity" to ≥25 for these demographics.',
  d_egfr: 'Estimated GFR via CKD-EPI 2021.', r_egfr_no: 'Normal/Mildly Decreased (≥ 60).', a_egfr_no: '• Routine monitoring of renal function.<br>• Optimize blood pressure and glucose control.', rx_egfr_no_n: 'Standard Care', rx_egfr_no_d: 'If proteinuria present, initiate ACE inhibitor or ARB.', r_egfr_md: 'Moderate CKD (GFR 30 - 59).', a_egfr_md: '• Evaluate for complications (anemia, bone disease).<br>• Adjust renally cleared medications.', rx_egfr_md_n: 'Renal Dose Adjustments', rx_egfr_md_d: 'Dose reduce DOACs, Metformin, and specific antibiotics. Avoid NSAIDs.', r_egfr_se: 'Severe CKD / Kidney Failure (< 30).', a_egfr_se: '• Mandatory Nephrology consultation.<br>• Prepare for Renal Replacement Therapy (RRT).', rx_egfr_se_n: 'Strict Nephro-Protection', rx_egfr_se_d: 'Discontinue Metformin. Manage hyperkalemia actively.', egfr_info_title: 'Evidence & Insights: eGFR (CKD-EPI)', egfr_info_p1: 'Overview: The 2021 CKD-EPI equation removes the controversial race multiplier, providing the most accurate reflection of true Glomerular Filtration Rate currently available.', egfr_info_p2: 'Clinical Pearls: eGFR formulas are inaccurate in acute kidney injury (AKI) where creatinine is not in steady state. It is also unreliable in amputees, severe malnutrition, or extremes of muscle mass.', egfr_info_p3: 'Guidelines: An eGFR <60 mL/min persisting for >3 months establishes Chronic Kidney Disease (CKD). It is mandatory to check eGFR before prescribing renally cleared drugs.',
  d_mews: 'Early detection of clinical deterioration.', r_mews_lo: 'Physiologically stable.', a_mews_lo: '• Continue routine ward observations.<br>• Maintain current therapeutic management plan.', rx_mews_lo_n: 'No escalation required', rx_mews_lo_d: 'Continue charted medications.', r_mews_md: 'Potential physiological instability.', a_mews_md: '• Escalate observation frequency to 1-2 hourly.<br>• Request medical review within 30 minutes.', rx_mews_md_n: 'Targeted Resuscitation', rx_mews_md_d: 'Titrate oxygen to SpO2 >94%. Conservative IV fluid bolus if hypotensive.', r_mews_hi: 'Critical physiological deterioration.', a_mews_hi: '• Immediate emergency medical review.<br>• Activate Rapid Response Team (RRT).', rx_mews_hi_n: 'ALS Standby', rx_mews_hi_d: 'Aggressive fluid resuscitation. Prepare crash cart.', mews_info_title: 'Evidence & Insights: MEWS', mews_info_p1: 'Overview: A bedside "track-and-trigger" scoring system used universally to identify catastrophic clinical deterioration hours before cardiac arrest occurs.', mews_info_p2: 'Clinical Pearls: Tachypnea (increased respiratory rate) is highly sensitive and often the very first indicator of systemic distress or metabolic acidosis. Temperature is the least predictive alone.', mews_info_p3: 'Next Steps: A score of ≥5 triggers mandatory Rapid Response Team (RRT) activation globally, indicating impending need for ICU transfer.',
  d_centor: 'Clinical probability of Strep pharyngitis.', r_centor_lo: 'Viral Pharyngitis likely.', a_centor_lo: '• Provide symptomatic relief.<br>• Do NOT perform throat culture.', rx_centor_lo_n: 'Symptomatic Care Only', rx_centor_lo_d: 'Acetaminophen or Ibuprofen. Avoid antibiotics.', r_centor_md: 'Possible Strep Pharyngitis.', a_centor_md: '• Perform Rapid Antigen Detection Test (RADT).<br>• If positive, treat with antibiotics.', rx_centor_md_n: 'Hold Antibiotics', rx_centor_md_d: 'Empiric antibiotics not recommended until laboratory confirmation.', r_centor_hi: 'Strep Highly Likely.', a_centor_hi: '• Consider empiric antibiotics if RADT is unavailable.<br>• Exclude infectious mononucleosis.', rx_centor_hi_n: 'Antimicrobial Therapy', rx_centor_hi_d: 'Penicillin V 500mg QID for 10 days (or Amoxicillin).', centor_info_title: 'Evidence & Insights: Centor Criteria', centor_info_p1: 'Overview: Estimates the probability that pharyngitis is caused by Group A beta-hemolytic Streptococcus (GAS).', centor_info_p2: 'Clinical Pearls: Its primary power is negative predictive value—best used to *rule out* Strep and avoid unnecessary antibiotics.', centor_info_p3: 'Guidelines: Score 0-1: No testing. Score 2-3: Perform Rapid Strep Test. Score 4-5: High probability; empiric antibiotics justified.',
  d_nihss: 'Quantify stroke severity to guide thrombolysis.', r_nihss_mi: 'Minor Stroke (1-4).', a_nihss_mi: '• Admit to specialized Stroke Unit.<br>• Evaluate for secondary stroke prevention.', rx_nihss_mi_n: 'Antiplatelet Therapy', rx_nihss_mi_d: 'Aspirin 300mg stat. Evaluate risk/benefit for IV thrombolysis.', r_nihss_mo: 'Moderate Stroke (5-15).', a_nihss_mo: '• Urgent evaluation for IV thrombolysis.<br>• CT Angiography to assess for LVO.', rx_nihss_mo_n: 'Reperfusion Evaluation', rx_nihss_mo_d: 'IV Alteplase (0.9 mg/kg) if presenting < 4.5 hours from onset.', r_nihss_ms: 'Moderate-Severe Stroke (16-20).', a_nihss_ms: '• High probability of LVO; activate endovascular team.<br>• Prepare for emergent thrombectomy.', rx_nihss_ms_n: 'Combined Reperfusion', rx_nihss_ms_d: 'Bridging IV Thrombolysis followed immediately by Mechanical Thrombectomy.', r_nihss_se: 'Severe Stroke (> 20).', a_nihss_se: '• Very high risk of cerebral edema and hemorrhagic transformation.<br>• Consider decompressive hemicraniectomy.', rx_nihss_se_n: 'ICU Management', rx_nihss_se_d: 'Withhold thrombolysis if extensive early ischemic changes on CT.', nihss_info_title: 'Evidence & Insights: NIHSS', nihss_info_p1: 'Overview: The international gold standard 15-item quantitative measure used to rapidly evaluate the severity of acute stroke.', nihss_info_p2: 'Clinical Pearls: The scale is heavily weighted toward anterior circulation (MCA) strokes. It may artificially score low in posterior strokes.', nihss_info_p3: 'Next Steps: Essential for determining eligibility for IV Alteplase (tPA) and Endovascular Thrombectomy (EVT).',
  d_sofa: 'Define sepsis via organ failure assessment.', r_sofa_lo: 'Low Sepsis Mortality Risk.', a_sofa_lo: '• Identify and treat underlying source of infection.<br>• Continue standard ward-level monitoring.', rx_sofa_lo_n: 'Targeted Antimicrobials', rx_sofa_lo_d: 'Initiate appropriate antibiotics based on suspected source.', r_sofa_md: 'Moderate Organ Dysfunction.', a_sofa_md: '• Sepsis formally diagnosed (Sepsis-3).<br>• Initiate Sepsis Six pathway immediately.', rx_sofa_md_n: 'Sepsis Resuscitation', rx_sofa_md_d: 'Administer 30 mL/kg IV crystalloid fluid if hypotensive. Broad-spectrum IV antibiotics.', r_sofa_hi: 'Severe Multi-Organ Failure (Septic Shock).', a_sofa_hi: '• Mandatory ICU admission.<br>• Central venous access and arterial line insertion.', rx_sofa_hi_n: 'Vasopressor Support', rx_sofa_hi_d: 'Norepinephrine as first-line agent to maintain MAP > 65 mmHg.', sofa_info_title: 'Evidence & Insights: SOFA', sofa_info_p1: 'Overview: The Sequential Organ Failure Assessment (SOFA) is the foundation of the Sepsis-3 diagnostic criteria.', sofa_info_p2: 'Clinical Pearls: Unlike the rapid bedside qSOFA, the full SOFA score requires comprehensive laboratory inputs to objectify dysfunction.', sofa_info_p3: 'Guidelines: An acute increase of ≥ 2 points from the patient\'s baseline establishes a formal clinical diagnosis of Sepsis.',
  d_ranson: 'Predictive algorithm for acute pancreatitis.', r_ranson_lo: 'Mild Acute Pancreatitis.', a_ranson_lo: '• Admit to general medical ward.<br>• Initiate early enteral nutrition when nausea subsides.', rx_ranson_lo_n: 'Supportive Care', rx_ranson_lo_d: 'Isotonic IV fluids. IV Opioids (e.g., Morphine) for pain control.', r_ranson_md: 'Moderate-to-Severe Pancreatitis.', a_ranson_md: '• Step-down or ICU admission.<br>• Aggressive, goal-directed fluid resuscitation.', rx_ranson_md_n: 'Aggressive Resuscitation', rx_ranson_md_d: 'Lactated Ringer’s preferred at 250-500 mL/hr. Correct hypocalcemia.', r_ranson_hi: 'Severe Acute Pancreatitis (High Mortality).', a_ranson_hi: '• Mandatory ICU admission.<br>• Surgical and gastroenterology consultations.', rx_ranson_hi_n: 'Critical Care Management', rx_ranson_hi_d: 'Vasopressors if fluids fail. Consider antibiotics ONLY if necrosis becomes infected.', ranson_info_title: 'Evidence & Insights: Ranson Criteria', ranson_info_p1: 'Overview: The original 1974 predictive model designed to estimate mortality and severity in acute pancreatitis.', ranson_info_p2: 'Clinical Pearls: The score requires a full 48 hours to complete. Markers like massive fluid sequestration (>6L) reflect severe retroperitoneal necrosis.', ranson_info_p3: 'Next Steps: A score ≥3 signifies severe acute pancreatitis. Modern practice often combines Ranson with APACHE II or BISAP.',
  d_psi: 'Mortality stratification for CAP.', r_psi_1: 'Risk Class I (Lowest Mortality).', a_psi_1: '• Safe for outpatient management.<br>• Discharge home with clear return precautions.', rx_psi_1_n: 'Outpatient Oral ABX', rx_psi_1_d: 'Oral Macrolide (Azithromycin) or Doxycycline monotherapy.', r_psi_2: 'Risk Class II (Low Mortality).', a_psi_2: '• Outpatient management recommended.<br>• Ensure patient has adequate social support.', rx_psi_2_n: 'Outpatient Oral ABX', rx_psi_2_d: 'Oral Amoxicillin or Macrolide.', r_psi_3: 'Risk Class III (Moderate Mortality).', a_psi_3: '• Consider hospital admission to observation unit or short-stay ward.', rx_psi_3_n: 'Short-Stay ABX', rx_psi_3_d: 'Oral or IV Respiratory Fluoroquinolone OR Beta-lactam + Macrolide combination.', r_psi_4: 'Risk Class IV (High Mortality).', a_psi_4: '• Formal inpatient admission required.<br>• Obtain comprehensive blood and sputum cultures.', rx_psi_4_n: 'Inpatient IV ABX', rx_psi_4_d: 'IV Ceftriaxone PLUS Azithromycin OR IV Levofloxacin.', r_psi_5: 'Risk Class V (Very High Mortality).', a_psi_5: '• Direct ICU admission strongly recommended.<br>• Aggressive hemodynamic resuscitation.', rx_psi_5_n: 'ICU Broad-Spectrum ABX', rx_psi_5_d: 'IV Beta-Lactam + IV Macrolide. Cover for MRSA/Pseudomonas if specific risk factors exist.', psi_info_title: 'Evidence & Insights: PSI/PORT', psi_info_p1: 'Overview: A robust, age-weighted clinical prediction rule used to calculate the 30-day mortality probability for CAP.', psi_info_p2: 'Clinical Pearls: While much more complex than CURB-65, it is statistically superior at identifying truly low-risk patients for safe discharge.', psi_info_p3: 'Guidelines: Classes I and II can be safely discharged. Classes IV and V demand formal inpatient admission, with Class V requiring Critical Care.'
},

ru:{
  hero_desc: '15 доказательных калькуляторов с мнемоникой на 3 языках. Быстро, надежно и удобно — всё, что нужно у постели больного.',
  stat_calc: 'Калькуляторов',
  stat_lang: 'Языка',
  stat_free: 'Бесплатно',
  all_label: 'Все калькуляторы',

  // --- UI, LABELS & MNEMONICS ---
  badge: 'КЛИНИЧЕСКИЕ ИНСТРУМЕНТЫ', h1a: 'Ward', h1b: 'Calc', sub: 'Доказательные медицинские калькуляторы для ежедневной практики.', badge_stu: 'СОЗДАНО СТУДЕНТОМ-МЕДИКОМ · ДЛЯ ВРАЧЕЙ', h1_main: 'Клинические инструменты', h1_sub: 'для обходов', search_ph: 'Поиск (напр. ШКГ, ИМТ)...', alert_msg: 'Пожалуйста, заполните все поля.', btn: 'Рассчитать', tab_i: 'Интерпретация', tab_a: 'План действий', tab_d: 'Терапия (Rx)', yes: 'Да', no: 'Нет', YES: 'Да', NO: 'Нет', mnem_all: 'Мнемоника / Запоминание', MNEM_ALL: 'Мнемоника / Запоминание',
  sp_neuro: 'Неврология', sp_ped: 'Педиатрия', sp_gen: 'Общие', sp_resp: 'Пульмонология', sp_cardio: 'Кардиология', sp_gastro: 'Гастро', sp_id: 'Инф. болезни', sev_lo: 'НИЗКИЙ РИСК', sev_md: 'СРЕДНИЙ РИСК', sev_hi: 'ВЫСОКИЙ РИСК',
  ft_about: 'О нас', ft_contact: 'Контакты', ft_disc: 'Отказ', ft_terms: 'Условия', ft_privacy: 'Конфиденциальность', ft_rights: '© 2026 WardCalc. Все права защищены.',
  nav_about: 'О проекте WardCalc', about_p1: 'WardCalc — это комплексная система поддержки принятия клинических решений, разработанная Мухаммадом Сабиром Али, студентом выпускного курса Бухарского государственного медицинского института.', about_h2: 'Наша миссия', about_p2: 'Оцифровать признанные международные шкалы в интуитивный мобильный интерфейс, помогая врачам принимать безопасные решения.', about_h3: 'Образовательная цель', about_p3: 'Приложение предназначено исключительно для образовательных и справочных целей. Оно должно помогать, а не заменять клиническое мышление.',
  nav_contact: 'Свяжитесь с нами', contact_p1: 'Если у вас есть отзывы или вы столкнулись с проблемой, свяжитесь с нами.', contact_p2: 'Для поддержки обращайтесь через наш официальный репозиторий GitHub.',
  nav_disc: 'Отказ от ответственности', disc_p1: 'Предоставленные рекомендации и дозировки предназначены исключительно для образовательных целей и не являются официальным медицинским протоколом.', disc_p2: 'Врачи должны полагаться на собственное независимое клиническое суждение. Мухаммад Сабир Али не несет ответственности за решения, принятые на основе этого приложения.',
  nav_terms: 'Условия использования', terms_p1: 'Сервис предоставляется «как есть» без гарантий.', terms_p2: 'Пользователи несут ответственность за проверку точности расчетов перед применением их в практике.',
  nav_privacy: 'Конфиденциальность', privacy_p1: 'WardCalc работает полностью локально в вашем браузере.', privacy_p2: 'Мы не собираем и не храним личные медицинские данные пациентов.',

  // DOUBLE-MAPPED FACTORS
  f_eye:'Открывание глаз', f_verbal:'Речевой ответ', f_motor:'Двигательный ответ', g_e4:'Самопроизвольно (4)', g_e3:'На голос (3)', g_e2:'На боль (2)', g_e1:'Нет (1)', g_v5:'Ориентирован (5)', g_v4:'Спутанная (4)', g_v3:'Слова (3)', g_v2:'Звуки (2)', g_v1:'Нет (1)', g_m6:'Выполняет (6)', g_m5:'Локализует (5)', g_m4:'Отдёргивание (4)', g_m3:'Сгибание (3)', g_m2:'Разгибание (2)', g_m1:'Нет (1)',
  f_appear:'Цвет кожи', f_pulse:'Пульс', f_grimace:'Гримаса', f_activity:'Тонус', f_resp_a:'Дыхание', a_a2:'Розовый (2)', a_a1:'Акроцианоз (1)', a_a0:'Бледный (0)', a_p2:'≥ 100 (2)', a_p1:'< 100 (1)', a_p0:'Нет (0)', a_g2:'Крик (2)', a_g1:'Гримаса (1)', a_g0:'Нет (0)', a_c2:'Активный (2)', a_c1:'Сгибание (1)', a_c0:'Вялый (0)', a_r2:'Громкий (2)', a_r1:'Слабое (1)', a_r0:'Нет (0)',
  f_cancer:'Активный рак', d1:'Активный рак', f_paralysis:'Паралич или парез', d2:'Паралич или парез', f_bedridden:'Постельный режим > 3 дней', d3:'Постельный режим > 3 дней', f_tenderness:'Локальная болезненность', d4:'Локальная болезненность', f_swelling_entire:'Отек всей ноги', d5:'Отек всей ноги', f_swelling_calf:'Отек голени > 3 см', d6:'Отек голени > 3 см', f_pitting:'Ямкообразующий отек', d7:'Ямкообразующий отек', f_collateral:'Коллатеральные вены', d8:'Коллатеральные вены', f_alt_dx:'Альтернативный диагноз (-2)', d9:'Альтернативный диагноз (-2)',
  f_pe_dvt:'Признаки ТГВ', p1:'Признаки ТГВ', f_pe_alt:'Альтернатива маловероятна', p2:'Альтернатива маловероятна', f_pe_hr:'ЧСС > 100', p3:'ЧСС > 100', f_pe_immob:'Иммобилизация (> 3 дней)', p4:'Иммобилизация (> 3 дней)', f_pe_hx:'ТЭЛА/ТГВ в анамнезе', p5:'ТЭЛА/ТГВ в анамнезе', f_pe_hemop:'Кровохарканье', p6:'Кровохарканье', f_pe_malig:'Онкология', p7:'Онкология',
  f_confusion:'Спутанность', c1:'Спутанность', f_urea:'Мочевина > 7 ммоль/л', c2:'Мочевина > 7 ммоль/л', f_rr30:'ЧДД ≥ 30', c3:'ЧДД ≥ 30', f_bp_low:'АД < 90/60', c4:'АД < 90/60', f_age65:'Возраст ≥ 65', c5:'Возраст ≥ 65',
  ch_c:'C: Сердечная недостаточность (+1)', ch_h:'H: Гипертензия (+1)', ch_a2:'A: Возраст ≥ 75 (+2)', ch_d:'D: Диабет (+1)', ch_s2:'S: Инсульт/ТИА (+2)', ch_v:'V: Сосудистые заб. (+1)', ch_a1:'A: Возраст 65-74 (+1)', ch_sex:'S: Женский пол (+1)',
  f_bili:'Билирубин (мкмоль/л)', f_alb:'Альбумин (г/л)', f_pt:'ПВ / МНО', f_ascites:'Асцит', f_enceph:'Энцефалопатия', cp_b1:'< 34', cp_b2:'34–50', cp_b3:'> 50', cp_a1:'> 35', cp_a2:'28–35', cp_a3:'< 28', cp_p1:'< 1.7', cp_p2:'1.7–2.3', cp_p3:'> 2.3', cp_as2:'Легкий/Средний', cp_as3:'Тяжелый', cp_e2:'I–II ст.', cp_e3:'III–IV ст.',
  f_weight:'Вес (кг)', f_height:'Рост (см)', f_cr:'Креатинин', f_age:'Возраст', f_sex:'Пол', sex_m:'Мужской', sex_f:'Женский',
  f_mews_rr:'ЧДД', f_mews_hr:'ЧСС', f_mews_sbp:'Сист. АД', f_mews_temp:'Температура', f_mews_avpu:'Сознание (AVPU)',
  f_cough_a:'Отсутствие кашля', f_exudates:'Экссудат', f_lymph:'Болезненные лимфоузлы', f_temp38:'Темп > 38.0°C', f_c_age:'Возрастная группа', c_age_1:'3-14 лет (+1)', c_age_2:'15-44 лет (0)', c_age_3:'≥ 45 лет (-1)',
  f_nihss_score:'Балл NIHSS (0-42)',
  f_pao2:'PaO2/FiO2', f_plt:'Тромбоциты', f_bili_sofa:'Билирубин', f_map:'САД / Вазопрессоры', f_gcs_sofa:'ШКГ', f_cr_sofa:'Креатинин/Диурез',
  f_age55:'Возраст > 55', f_wbc:'Лейкоциты > 16 тыс.', f_glu:'Глюкоза > 11.1', f_ldh:'ЛДГ > 350', f_ast:'АСТ > 250', f_hct_drop:'Гематокрит сниж. > 10%', f_bun_rise:'Мочевина выросла', f_ca_low:'Кальций < 2.0', f_pao2_low:'PaO2 < 60', f_base_def:'Дефицит оснований > 4', f_fluid_seq:'Потеря жидкости > 6 л',
  f_psi_age:'Возраст (лет)', psi_age:'Возраст (лет)', f_psi_sex:'Пол', psi_sex:'Пол', f_psi_nh:'Дом престарелых', psi_nh:'Дом престарелых', f_psi_neo:'Онкология', psi_neo:'Онкология', f_psi_liv:'Заболевания печени', psi_liv:'Заболевания печени', f_psi_chf:'Сердечная недостаточность', psi_chf:'Сердечная недостаточность', f_psi_cvd:'Инсульт', psi_cvd:'Инсульт', f_psi_ren:'Болезни почек', psi_ren:'Болезни почек', f_psi_ams:'Нарушение сознания', psi_ams:'Нарушение сознания', f_psi_rr:'ЧДД ≥ 30', psi_rr:'ЧДД ≥ 30', f_psi_sbp:'САД < 90', psi_sbp:'САД < 90', f_psi_temp:'Темп < 35 или ≥ 40', psi_temp:'Темп < 35 или ≥ 40', f_psi_pulse:'Пульс ≥ 125', psi_pulse:'Пульс ≥ 125', f_psi_ph:'pH < 7.35', psi_ph:'pH < 7.35', f_psi_bun:'Мочевина ≥ 10.7', psi_bun:'Мочевина ≥ 10.7', f_psi_na:'Натрий < 130', psi_na:'Натрий < 130', f_psi_gluc:'Глюкоза ≥ 13.9', psi_gluc:'Глюкоза ≥ 13.9', f_psi_hct:'Гематокрит < 30%', psi_hct:'Гематокрит < 30%', f_psi_pao2:'PaO2 < 60', psi_pao2:'PaO2 < 60', f_psi_eff:'Плевральный выпот', psi_eff:'Плевральный выпот',

  // NEW NIHSS FULL QUESTIONS (Russian)
  n1a_q:'1a. Уровень сознания', n1a_0:'0: В ясном сознании', n1a_1:'1: Оглушение', n1a_2:'2: Сопор', n1a_3:'3: Кома',
  n1b_q:'1b. Вопросы (Месяц/Возраст)', n1b_0:'0: Оба верны', n1b_1:'1: Один верен', n1b_2:'2: Ни одного',
  n1c_q:'1c. Команды (Глаза, кулак)', n1c_0:'0: Обе выполнены', n1c_1:'1: Одна выполнена', n1c_2:'2: Ни одной',
  n2_q:'2. Движение глаз', n2_0:'0: Норма', n2_1:'1: Частичный парез взора', n2_2:'2: Насильственное отклонение',
  n3_q:'3. Поля зрения', n3_0:'0: Норма', n3_1:'1: Частичная гемианопсия', n3_2:'2: Полная гемианопсия', n3_3:'3: Билатеральная слепота',
  n4_q:'4. Парез лица', n4_0:'0: Норма', n4_1:'1: Сглаженность складок', n4_2:'2: Частичный паралич', n4_3:'3: Полный паралич',
  n5a_q:'5a. Левая рука', n5a_0:'0: Норма', n5a_1:'1: Опускание', n5a_2:'2: Удержание против тяжести', n5a_3:'3: Без преодоления тяжести', n5a_4:'4: Нет движений',
  n5b_q:'5b. Правая рука', n5b_0:'0: Норма', n5b_1:'1: Опускание', n5b_2:'2: Удержание против тяжести', n5b_3:'3: Без преодоления тяжести', n5b_4:'4: Нет движений',
  n6a_q:'6a. Левая нога', n6a_0:'0: Норма', n6a_1:'1: Опускание', n6a_2:'2: Удержание против тяжести', n6a_3:'3: Без преодоления тяжести', n6a_4:'4: Нет движений',
  n6b_q:'6b. Правая нога', n6b_0:'0: Норма', n6b_1:'1: Опускание', n6b_2:'2: Удержание против тяжести', n6b_3:'3: Без преодоления тяжести', n6b_4:'4: Нет движений',
  n7_q:'7. Атаксия', n7_0:'0: Нет', n7_1:'1: В 1 конечности', n7_2:'2: В 2 конечностях',
  n8_q:'8. Чувствительность', n8_0:'0: Норма', n8_1:'1: Частичная потеря', n8_2:'2: Полная потеря',
  n9_q:'9. Речь', n9_0:'0: Норма', n9_1:'1: Легкая/Умеренная афазия', n9_2:'2: Тяжелая афазия', n9_3:'3: Немота/Глобальная',
  n10_q:'10. Дизартрия', n10_0:'0: Норма', n10_1:'1: Легкая/Умеренная', n10_2:'2: Тяжелая/Ануртрия',
  n11_q:'11. Игнорирование', n11_0:'0: Норма', n11_1:'1: Частичное игнорирование', n11_2:'2: Полное игнорирование',

  // --- EXPERT CLINICAL TEXT (Russian) ---
  d_gcs: 'Базовая оценка уровня сознания. Первый показатель при травмах.', r_gcs_mi: 'Легкая ЧМТ (ШКГ 13-15).', a_gcs_mi: '• Полный неврологический осмотр.<br>• Наблюдение каждые 30-60 минут.', rx_gcs_mi_n: 'Симптоматическая терапия', rx_gcs_mi_d: 'Анальгезия (Парацетамол). Избегать седативных опиоидов.', r_gcs_mo: 'Умеренная ЧМТ (ШКГ 9-12). Высокий риск ишемии мозга.', a_gcs_mo: '• Срочная КТ головы.<br>• Консультация нейрохирурга.', rx_gcs_mo_n: 'Нейропротекция', rx_gcs_mo_d: 'Рассмотреть Леветирацетам (500 мг в/в).', r_gcs_se: 'Тяжелая ЧМТ (ШКГ ≤ 8). Риск дислокации.', a_gcs_se: '• НЕМЕДЛЕННАЯ интубация трахеи.<br>• Госпитализация в ОРИТ.', rx_gcs_se_n: 'Терапия ВЧД', rx_gcs_se_d: 'Пропофол/Кетамин. При дислокации: Маннитол 20% или гипертонический NaCl 3%.', gcs_info_title: 'Анализ: Шкала Глазго', gcs_info_p1: 'Обзор: Шкала комы Глазго стандартизирует оценку сознания при острой травме мозга и системных заболеваниях.', gcs_info_p2: 'Жемчужины: Двигательный ответ — самый надежный предиктор исхода. При асимметрии всегда оценивайте ЛУЧШИЙ ответ.', gcs_info_p3: 'Тактика: ШКГ 8 и ниже означает кому. Это абсолютное показание для экстренной интубации трахеи.',
  d_apgar: 'Оценка новорожденного на 1 и 5 минутах. Руководство по реанимации.', r_apgar_no: 'Нормальная адаптация.', a_apgar_no: '• Стандартный уход.<br>• Контакт кожа-к-коже.', rx_apgar_no_n: 'Профилактика', rx_apgar_no_d: 'Витамин К 1 мг в/м.', r_apgar_mo: 'Умеренная депрессия.', a_apgar_mo: '• Тактильная стимуляция.<br>• Подача кислорода.', rx_apgar_mo_n: 'Оксигенотерапия', rx_apgar_mo_d: 'Титровать кислород по сатурации.', r_apgar_cr: 'Критическое состояние.', a_apgar_cr: '• Немедленная реанимация (ИВЛ через маску).', rx_apgar_cr_n: 'Препараты', rx_apgar_cr_d: 'При ЧСС < 60 после вентиляции: Эпинефрин в/в.', apgar_info_title: 'Анализ: Шкала Апгар', apgar_info_p1: 'Обзор: Оценка на 1-й минуте отражает переносимость родов, на 5-й минуте — адаптацию к внеутробной жизни.', apgar_info_p2: 'Жемчужины: Критерии НЕ равнозначны. Пульс и дыхание жизненно важны, тогда как цвет кожи наименее надежен.', apgar_info_p3: 'Тактика: Оценка ≤ 3 на 5-й минуте требует агрессивной неонатальной реанимации и продолжения оценки каждые 5 минут.',
  d_dvt: 'Оценка вероятности Тромбоза Глубоких Вен (ТГВ).', r_dvt_lo: 'ТГВ маловероятен.', a_dvt_lo: '• Анализ на D-димер.<br>• При (-) ТГВ исключен.', rx_dvt_lo_n: 'Антикоагулянты не нужны', rx_dvt_lo_d: 'Эмпирическая терапия не показана.', r_dvt_md: 'Умеренная вероятность.', a_dvt_md: '• D-димер.<br>• При (+) УЗИ вен.', rx_dvt_md_n: 'Ожидание УЗИ', rx_dvt_md_d: 'Терапия только при задержке УЗИ > 4 часов.', r_dvt_hi: 'Высокая вероятность ТГВ.', a_dvt_hi: '• Срочное УЗИ вен нижних конечностей.', rx_dvt_hi_n: 'Эмпирическая терапия', rx_dvt_hi_d: 'Начать НОАК (Апиксабан) или НМГ (Эноксапарин).', dvt_info_title: 'Анализ: ТГВ Уэллса', dvt_info_p1: 'Обзор: Правило помогает оценить вероятность ТГВ до назначения дорогостоящего УЗИ или опасных антикоагулянтов.', dvt_info_p2: 'Жемчужины: Критерий "Альтернативный диагноз" требует клинического мышления (исключите целлюлит, разрыв кисты Бейкера).', dvt_info_p3: 'Тактика: У пациентов низкого риска отрицательный D-димер исключает ТГВ. При высоком риске (≥2) D-димера недостаточно, нужно УЗИ.',
  d_pe: 'Расчет вероятности ТЭЛА перед назначением КТ.', r_pe_lo: 'ТЭЛА маловероятна.', a_pe_lo: '• Правило PERC или D-димер.', rx_pe_lo_n: 'Терапия не показана', rx_pe_lo_d: 'Антикоагулянты противопоказаны.', r_pe_md: 'Умеренная вероятность.', a_pe_md: '• D-димер.<br>• При (+) показана КТ-ангиография.', rx_pe_md_n: 'Ожидание КТ', rx_pe_md_d: 'Ждать результатов КТ, если нет критической задержки.', r_pe_hi: 'Высокая вероятность ТЭЛА.', a_pe_hi: '• Срочная КТ-ангиография.<br>• Госпитализация.', rx_pe_hi_n: 'Агрессивная терапия', rx_pe_hi_d: 'Немедленно начать НМГ или инфузию Гепарина в/в.', pe_info_title: 'Анализ: ТЭЛА Уэллса', pe_info_p1: 'Обзор: Стратифицирует риск ТЭЛА для предотвращения ненужной КТ-ангиографии и облучения.', pe_info_p2: 'Жемчужины: Тахикардия (>100) — сильный, но неспецифичный признак. Ищите признаки перегрузки правых отделов (S1Q3T3 на ЭКГ).', pe_info_p3: 'Тактика: При оценке >4 ТЭЛА "вероятна". Отрицательный D-димер не исключает диагноз, требуется КТ-АГ и эмпирические антикоагулянты.',
  d_curb65: 'Стратификация риска смертности при пневмонии (ВП).', r_curb_lo: 'Низкий риск смертности (< 2%).', a_curb_lo: '• Амбулаторное лечение.<br>• Контроль через 48 часов.', rx_curb_lo_n: 'Амбулаторные АБ', rx_curb_lo_d: 'Амоксициллин внутрь или Доксициклин (5-7 дней).', r_curb_md: 'Умеренный риск (~9%).', a_curb_md: '• Госпитализация в терапию.<br>• Посев крови/мокроты.', rx_curb_md_n: 'В/в АБТ', rx_curb_md_d: 'Амоксициллин/Клавуланат в/в + Кларитромицин.', r_curb_hi: 'Тяжелая пневмония.', a_curb_hi: '• Срочная госпитализация (ОРИТ).<br>• Готовность к ИВЛ.', rx_curb_hi_n: 'АБТ широкого спектра (ОРИТ)', rx_curb_hi_d: 'Цефтриаксон в/в ПЛЮС Макролид. Добавить защиту от MRSA.', curb_info_title: 'Анализ: CURB-65', curb_info_p1: 'Обзор: Валидированная шкала Британского торакального общества для прогноза 30-дневной смертности при внебольничной пневмонии.', curb_info_p2: 'Жемчужины: Мочевина > 7 ммоль/л отражает обезвоживание и гипоперфузию почек при сепсисе.', curb_info_p3: 'Тактика: 0-1 балл: амбулаторно. 2 балла: отделение терапии. 3+ балла: тяжелая пневмония (смертность до 40%), рассмотреть ОРИТ.',
  d_chads2: 'Стратификация риска инсульта при фибрилляции предсердий.', r_chads_lo: 'Низкий риск инсульта.', a_chads_lo: '• Оценка риска кровотечений (HAS-BLED).', rx_chads_lo_n: 'Терапия не нужна', rx_chads_lo_d: 'Антитромботическая терапия не рекомендована.', r_chads_md: 'Промежуточный риск.', a_chads_md: '• Индивидуальное решение совместно с пациентом.', rx_chads_md_n: 'Рассмотреть НОАК', rx_chads_md_d: 'Оценка пользы/риска.', r_chads_hi: 'Высокий риск инсульта.', a_chads_hi: '• Строгое показание к антикоагулянтам.', rx_chads_hi_n: 'Пожизненная терапия', rx_chads_hi_d: 'НОАК (Апиксабан/Ривароксабан) предпочтительнее Варфарина.', chads_info_title: 'Анализ: CHA₂DS₂-VASc', chads_info_p1: 'Обзор: Рекомендованная шкала AHA/ESC для оценки годового риска ишемического инсульта при неклапанной фибрилляции предсердий.', chads_info_p2: 'Жемчужины: "Неклапанная" означает отсутствие выраженного митрального стеноза или механического клапана.', chads_info_p3: 'Тактика: Оценка ≥2 (мужчины) или ≥3 (женщины) — абсолютное показание для НОАК.',
  d_cp: 'Прогностическая классификация тяжести цирроза.', r_cp_a: 'Класс A: Компенсация.', a_cp_a: '• Плановое наблюдение гепатолога.<br>• Скрининг варикоза вен пищевода.', rx_cp_a_n: 'Стандартный уход', rx_cp_a_d: 'Избегать гепатотоксичных лекарств.', r_cp_b: 'Класс B: Значительное нарушение.', a_cp_b: '• Формальная оценка гепатолога.<br>• Высокий хирургический риск.', rx_cp_b_n: 'Симптоматическое лечение', rx_cp_b_d: 'Бета-блокаторы для портальной гипертензии.', r_cp_c: 'Класс C: Декомпенсация.', a_cp_c: '• Срочная оценка на трансплантацию.<br>• Мониторинг перитонита.', rx_cp_c_n: 'Лечение осложнений', rx_cp_c_d: 'Спиронолактон при асците. Лактулоза при энцефалопатии.', cp_info_title: 'Анализ: Чайлд-Пью', cp_info_p1: 'Обзор: Классическая модель для оценки 1- и 2-летней выживаемости при циррозе и риска хирургического вмешательства.', cp_info_p2: 'Жемчужины: Субъективные критерии (асцит, энцефалопатия) могут быть временно улучшены мочегонными или лактулозой.', cp_info_p3: 'Тактика: Класс А дает выживаемость ~100%. Класс С означает терминальную стадию (выживаемость ~45%) и требует трансплантации.',
  d_bmi: 'Индекс массы тела с пороговыми значениями ВОЗ.', r_bmi_un: 'Дефицит веса (< 18.5).', a_bmi_un: '• Оценка питания.<br>• Исключить онкологию/гипертиреоз.', rx_bmi_un_n: 'Нутритивная поддержка', rx_bmi_un_d: 'Высококалорийное питание.', r_bmi_no: 'Нормальный вес.', a_bmi_no: '• Здоровый образ жизни.<br>• Ежегодный скрининг.', rx_bmi_no_n: 'Профилактика', rx_bmi_no_d: 'Лекарства не требуются.', r_bmi_ov: 'Избыточный вес.', a_bmi_ov: '• Снижение веса на 5-10%.<br>• Скрининг на диабет.', rx_bmi_ov_n: 'Оптимизация', rx_bmi_ov_d: 'Диета и спорт. Фармакотерапия редко показана.', r_bmi_ob1: 'Ожирение I.', a_bmi_ob1: '• Интенсивное изменение образа жизни.', rx_bmi_ob1_n: 'Фармакотерапия', rx_bmi_ob1_d: 'Агонисты ГПП-1 (Семаглутид) при наличии патологий.', r_bmi_ob2: 'Ожирение II+.', a_bmi_ob2: '• Высокий сердечный риск.<br>• Оценка бариатрической хирургии.', rx_bmi_ob2_n: 'Агрессивная терапия', rx_bmi_ob2_d: 'Максимальная мед. терапия, затем хирургическое вмешательство.', bmi_info_title: 'Анализ: Индекс массы тела', bmi_info_p1: 'Обзор: Стандарт ВОЗ для отслеживания антропометрических данных и базовой оценки кардиометаболического риска.', bmi_info_p2: 'Жемчужины: ИМТ не различает мышечную массу и жир. Может не выявить опасное висцеральное ожирение при нормальном весе.', bmi_info_p3: 'Тактика: У азиатских популяций более высокие риски при низком ИМТ (Избыточный вес начинается с 23, Ожирение с 25).',
  d_egfr: 'Скорость клубочковой фильтрации (CKD-EPI 2021).', r_egfr_no: 'Нормальная функция (≥ 60).', a_egfr_no: '• Рутинный контроль.<br>• Контроль АД и глюкозы.', rx_egfr_no_n: 'Стандарт', rx_egfr_no_d: 'Ингибиторы АПФ при протеинурии.', r_egfr_md: 'Умеренная ХБП (30-59).', a_egfr_md: '• Коррекция доз препаратов.<br>• Консультация нефролога при падении СКФ.', rx_egfr_md_n: 'Снижение доз', rx_egfr_md_d: 'Уменьшить дозу НОАК, Метформина. Избегать НПВС.', r_egfr_se: 'Тяжелая ХБП (< 30).', a_egfr_se: '• Срочная консультация нефролога.<br>• Подготовка к диализу (ЗПТ).', rx_egfr_se_n: 'Нефропротекция', rx_egfr_se_d: 'Отменить Метформин. Строгий контроль калия.', egfr_info_title: 'Анализ: рСКФ (CKD-EPI)', egfr_info_p1: 'Обзор: Формула CKD-EPI 2021 года устраняет расовый коэффициент, обеспечивая наиболее точное отражение истинной СКФ.', egfr_info_p2: 'Жемчужины: Формула неточна при остром повреждении почек (ОПП), у пациентов с ампутациями и при выраженной кахексии.', egfr_info_p3: 'Тактика: рСКФ < 60 мл/мин более 3 месяцев подтверждает Хроническую Болезнь Почек. Обязательна коррекция доз антибиотиков и НОАК.',
  d_mews: 'Риск клинического ухудшения.', r_mews_lo: 'Стабильно.', a_mews_lo: '• Рутинное наблюдение.', rx_mews_lo_n: 'Нет эскалации', rx_mews_lo_d: 'Текущий план лечения.', r_mews_md: 'Возможная нестабильность.', a_mews_md: '• Участить мониторинг.<br>• Вызов врача в течение 30 минут.', rx_mews_md_n: 'Целевая поддержка', rx_mews_md_d: 'Кислород до SpO2 >94%. Жидкость при гипотензии.', r_mews_hi: 'Критическое ухудшение.', a_mews_hi: '• Немедленный осмотр.<br>• Вызов реаниматологов.', rx_mews_hi_n: 'Реанимация', rx_mews_hi_d: 'Агрессивная инфузия. Готовность к интубации.', mews_info_title: 'Анализ: Шкала MEWS', mews_info_p1: 'Обзор: Физиологическая "track-and-trigger" система для выявления пациентов с риском катастрофического ухудшения до остановки сердца.', mews_info_p2: 'Жемчужины: Тахипноэ (учащенное дыхание) — самый ранний и чувствительный признак системного стресса или ацидоза.', mews_info_p3: 'Тактика: Оценка ≥ 5 баллов требует немедленного вызова реанимационной бригады и подготовки к переводу в ОРИТ.',
  d_centor: 'Клиническая вероятность стрептококкового фарингита.', r_centor_lo: 'Стрептококк маловероятен.', a_centor_lo: '• Симптоматическое лечение.<br>• Мазок не нужен.', rx_centor_lo_n: 'Без антибиотиков', rx_centor_lo_d: 'Парацетамол/Ибупрофен.', r_centor_md: 'Возможен стрептококк.', a_centor_md: '• Выполнить экспресс-тест (RADT).', rx_centor_md_n: 'Ждать результатов', rx_centor_md_d: 'Лечить только при (+) тесте.', r_centor_hi: 'Стрептококк высоко вероятен.', a_centor_hi: '• Эмпирические антибиотики оправданы.', rx_centor_hi_n: 'АБТ', rx_centor_hi_d: 'Пенициллин V 500 мг 4 р/д (10 дней).', centor_info_title: 'Анализ: Критерии Центора', centor_info_p1: 'Обзор: Модифицированные критерии Центора оценивают вероятность инфекции бета-гемолитическим стрептококком группы А (БГСА).', centor_info_p2: 'Жемчужины: Главная польза шкалы — отрицательная прогностическая ценность (чтобы ИСКЛЮЧИТЬ стрептококк и не давать антибиотики).', centor_info_p3: 'Тактика: 0-1 балл: без тестов и АБТ. 2-3 балла: экспресс-тест. 4-5 баллов: оправдано назначение Амоксициллина для профилактики ревматизма.',
  d_nihss: 'Оценка дефицита при инсульте.', r_nihss_mi: 'Легкий инсульт (1-4).', a_nihss_mi: '• Госпитализация в инсультное отделение.', rx_nihss_mi_n: 'Антиагреганты', rx_nihss_mi_d: 'Аспирин 300 мг.', r_nihss_mo: 'Средний инсульт (5-15).', a_nihss_mo: '• Оценка для в/в тромболизиса.<br>• КТ-АГ.', rx_nihss_mo_n: 'Реперфузия', rx_nihss_mo_d: 'Алтеплаза (0.9 мг/кг) если < 4.5 часов.', r_nihss_ms: 'Средне-тяжелый (16-20).', a_nihss_ms: '• Подготовка к тромбэктомии.', rx_nihss_ms_n: 'Комбинация', rx_nihss_ms_d: 'Тромболизис + Тромбэктомия.', r_nihss_se: 'Крайне тяжелый (> 20).', a_nihss_se: '• Риск отека мозга.<br>• Декомпрессивная краниэктомия.', rx_nihss_se_n: 'ОРИТ', rx_nihss_se_d: 'Жесткий контроль АД.', nihss_info_title: 'Анализ: Шкала NIHSS', nihss_info_p1: 'Обзор: Международный золотой стандарт (15 пунктов) для количественной оценки неврологического дефицита при остром инсульте.', nihss_info_p2: 'Жемчужины: Шкала предвзята к переднему кровообращению (СМА). При инсультах в стволе мозга или мозжечке баллы могут быть искусственно занижены.', nihss_info_p3: 'Тактика: Основной показатель для решения вопроса о внутривенном тромболизисе и эндоваскулярной тромбэктомии.',
  d_sofa: 'Оценка органной дисфункции (Sepsis-3).', r_sofa_lo: 'Низкий риск смертности.', a_sofa_lo: '• Найти источник инфекции.', rx_sofa_lo_n: 'Антибиотики', rx_sofa_lo_d: 'По локальным протоколам.', r_sofa_md: 'Органная дисфункция (Сепсис).', a_sofa_md: '• Протокол "Sepsis Six".', rx_sofa_md_n: 'Реанимация', rx_sofa_md_d: 'Инфузия 30 мл/кг. Широкий спектр АБ в/в.', r_sofa_hi: 'Септический шок.', a_sofa_hi: '• Обязательно ОРИТ.<br>• ЦВК.', rx_sofa_hi_n: 'Вазопрессоры', rx_sofa_hi_d: 'Норадреналин (целевое САД > 65).', sofa_info_title: 'Анализ: Шкала SOFA', sofa_info_p1: 'Обзор: Фундамент диагностических критериев Sepsis-3. Оценивает полиорганную недостаточность в условиях ОРИТ.', sofa_info_p2: 'Жемчужины: В отличие от быстрой шкалы qSOFA, полная шкала SOFA требует развернутых лабораторных данных (билирубин, тромбоциты, газы крови).', sofa_info_p3: 'Тактика: Острое повышение баллов SOFA на ≥ 2 от базового уровня подтверждает диагноз Сепсис (смертность минимум 10%).',
  d_ranson: 'Риск при остром панкреатите.', r_ranson_lo: 'Легкий панкреатит.', a_ranson_lo: '• Общая палата.<br>• Раннее питание.', rx_ranson_lo_n: 'Поддержка', rx_ranson_lo_d: 'Инфузии. Опиоиды для обезболивания.', r_ranson_md: 'Средне-тяжелый.', a_ranson_md: '• ОРИТ.<br>• Агрессивная инфузия.', rx_ranson_md_n: 'Агрессивная терапия', rx_ranson_md_d: 'Раствор Рингера/Хартмана 250-500 мл/ч.', r_ranson_hi: 'Высокая смертность.', a_ranson_hi: '• Мониторинг АРДС и некроза.', rx_ranson_hi_n: 'ОРИТ', rx_ranson_hi_d: 'АБ только при инфицированном некрозе.', ranson_info_title: 'Анализ: Критерии Рэнсона', ranson_info_p1: 'Обзор: Оригинальная модель 1974 года для прогноза тяжести и смертности при остром панкреатите.', ranson_info_p2: 'Жемчужины: Оценка занимает 48 часов. Массивная секвестрация жидкости (>6 л) и гипокальциемия отражают тяжелый ретроперитонеальный некроз.', ranson_info_p3: 'Тактика: Оценка ≥ 3 баллов указывает на тяжелый панкреатит. Требуется массивная инфузионная терапия под контролем диуреза.',
  d_psi: 'Стратификация при ВП.', r_psi_1: 'Класс I (Низкий).', a_psi_1: '• Амбулаторное лечение.', rx_psi_1_n: 'Пероральные АБ', rx_psi_1_d: 'Макролид или Доксициклин.', r_psi_2: 'Класс II (Низкий).', a_psi_2: '• Амбулаторное лечение.', rx_psi_2_n: 'Пероральные АБ', rx_psi_2_d: 'Амоксициллин.', r_psi_3: 'Класс III (Средний).', a_psi_3: '• Краткосрочная госпитализация.', rx_psi_3_n: 'Короткий курс', rx_psi_3_d: 'В/в или внутрь Фторхинолон.', r_psi_4: 'Класс IV (Высокий).', a_psi_4: '• Обязательная госпитализация.', rx_psi_4_n: 'В/в АБТ', rx_psi_4_d: 'Цефтриаксон + Азитромицин.', r_psi_5: 'Класс V (Критический).', a_psi_5: '• Госпитализация в ОРИТ.', rx_psi_5_n: 'Широкий спектр (ОРИТ)', rx_psi_5_d: 'Бета-лактам + Макролид в/в.', psi_info_title: 'Анализ: Шкала PSI/PORT', psi_info_p1: 'Обзор: Комплексное правило с поправкой на возраст для расчета 30-дневной смертности при внебольничной пневмонии.', psi_info_p2: 'Жемчужины: Хотя она сложнее CURB-65 (требует 20 переменных, включая газы крови), PSI статистически точнее выявляет пациентов низкого риска для безопасной выписки.', psi_info_p3: 'Тактика: Классы I-II могут лечиться амбулаторно. Класс III — наблюдение. Классы IV-V (смертность до 27%) абсолютно требуют госпитализации в стационар или ОРИТ.'
},

uz:{
  hero_desc: '3 tilda mnemonikaga ega 15 ta isbotlangan kalkulyatorlar. Tez, ishonchli va qulay — bemor yonida kerak bo\'lgan hamma narsa.',
  stat_calc: 'Kalkulyatorlar',
  stat_lang: 'Tillar',
  stat_free: 'Bepul',
  all_label: 'Barcha kalkulyatorlar',

  // --- UI, LABELS & MNEMONICS (Uzbek) ---
  badge: 'KLINIK VOSITALAR', h1a: 'Ward', h1b: 'Calc', sub: 'Kundalik amaliyot uchun isbotlarga asoslangan tibbiy kalkulyatorlar.', badge_stu: 'TIBBIYOT TALABASI TOMONIDAN YARATILGAN', h1_main: 'Klinik vositalar', h1_sub: 'palata aylanmalari uchun', search_ph: 'Qidiruv (masalan, GCS, BMI)...', alert_msg: 'Iltimos, barcha maydonlarni to\'ldiring.', btn: 'Hisoblash', tab_i: 'Talqin', tab_a: 'Harakat Rejasi', tab_d: 'Davolash (Rx)', yes: 'Ha', no: 'Yo\'q', YES: 'Ha', NO: 'Yo\'q', mnem_all: 'Mnemonika / Yodlash', MNEM_ALL: 'Mnemonika / Yodlash',
  sp_neuro: 'Nevrologiya', sp_ped: 'Pediatriya', sp_gen: 'Umumiy', sp_resp: 'Nafas tizimi', sp_cardio: 'Kardiologiya', sp_gastro: 'Gastroenterologiya', sp_id: 'Yuqumli kasal.', sev_lo: 'PAST XAVF', sev_md: 'O’RTACHA XAVF', sev_hi: 'YUQORI XAVF',
  ft_about: 'Biz haqimizda', ft_contact: 'Aloqa', ft_disc: 'Rad etish', ft_terms: 'Shartlar', ft_privacy: 'Maxfiylik', ft_rights: '© 2026 WardCalc. Barcha huquqlar himoyalangan.',
  nav_about: 'WardCalc haqida', about_p1: 'WardCalc - bu Buxoro davlat tibbiyot instituti bitiruvchi talabasi Muhammad Sabir Ali tomonidan ishlab chiqilgan kompleks klinik qarorlarni qabul qilishni qo\'llab-quvvatlash tizimi. Dastur tibbiyot xodimlariga tezkor, dalillarga asoslangan hisoblash vositalarini taqdim etadi.', about_h2: 'Bizning maqsadimiz', about_p2: 'Tibbiy ball tizimlarini intuitiv interfeysga aylantirish, shifokorlarga xavfsizroq va standartlashtirilgan qarorlar qabul qilish imkonini berishdir.', about_h3: 'Ta\'lim maqsadi', about_p3: 'U rasmiy klinik xulosani almashtirish uchun emas, yordam berish uchun mo\'ljallangan.',
  nav_contact: 'Aloqa va Qo\'llab-quvvatlash', contact_p1: 'Biz doimiy takomillashtirish tarafdorimiz. Agar sizda klinik mulohazalar yoki texnik muammolar bo\'lsa, biz bilan bog\'laning.', contact_p2: 'GitHub orqali murojaat qiling. Barcha xabarlar ko\'rib chiqiladi.',
  nav_disc: 'Rad etish', disc_p1: 'Taqdim etilgan tavsiyalar faqat ta\'lim maqsadida bo\'lib, rasmiy tibbiy bayonnoma hisoblanmaydi.', disc_p2: 'Shifokorlar o\'zlarining mustaqil klinik xulosalariga tayanishlari shart. Muhammad Sabir Ali ushbu dastur natijalariga asoslangan qarorlar uchun javobgar emas.',
  nav_terms: 'Foydalanish shartlari', terms_p1: 'Ushbu xizmat hech qanday kafolatsiz taqdim etiladi.', terms_p2: 'Hisob-kitoblar aniqligini tekshirish foydalanuvchi javobgarligida.',
  nav_privacy: 'Maxfiylik siyosati', privacy_p1: 'WardCalc to\'liq mijoz tomonida (lokal ravishda brauzeringizda) ishlaydi.', privacy_p2: 'Biz bemorni identifikatsiya qiluvchi hech qanday ma\'lumotlarni yig\'maymiz.',

  // DOUBLE-MAPPED FACTORS (Uzbek)
  f_eye:"Ko'z ochilishi", f_verbal:"Og'zaki javob", f_motor:'Harakat javobi', g_e4:'O\'z-o\'zidan (4)', g_e3:'Ovozga (3)', g_e2:'Og\'riqqa (2)', g_e1:'Yo\'q (1)', g_v5:'Mo\'ljallangan (5)', g_v4:'Chalkash (4)', g_v3:'So\'zlar (3)', g_v2:'Tovushlar (2)', g_v1:'Yo\'q (1)', g_m6:'Bajaradi (6)', g_m5:'Lokalizatsiya (5)', g_m4:'Tortib olish (4)', g_m3:'Bukilish (3)', g_m2:'Yozilish (2)', g_m1:'Yo\'q (1)',
  f_appear:'Teri rangi', f_pulse:'Puls', f_grimace:'Grimasa', f_activity:'Aktivlik', f_resp_a:'Nafas', a_a2:'Pushti (2)', a_a1:'Ko\'k (1)', a_a0:'Oq (0)', a_p2:'≥ 100 (2)', a_p1:'< 100 (1)', a_p0:'Yo\'q (0)', a_g2:'Yig\'lash (2)', a_g1:'Grimasa (1)', a_g0:'Yo\'q (0)', a_c2:'Faol (2)', a_c1:'Bukilish (1)', a_c0:'Bo\'sh (0)', a_r2:'Yig\'i (2)', a_r1:'Sust (1)', a_r0:'Yo\'q (0)',
  f_cancer:'Saraton', d1:'Saraton', f_paralysis:'Paralich', d2:'Paralich', f_bedridden:'Yotoq rejimi > 3 kun', d3:'Yotoq rejimi > 3 kun', f_tenderness:'Og\'riq', d4:'Og\'riq', f_swelling_entire:'Oyoq shishi', d5:'Oyoq shishi', f_swelling_calf:'Boldir shishi > 3 sm', d6:'Boldir shishi > 3 sm', f_pitting:'Chuqurcha', d7:'Chuqurcha', f_collateral:'Venalar', d8:'Venalar', f_alt_dx:'Boshqa tashxis (-2)', d9:'Boshqa tashxis (-2)',
  f_pe_dvt:'DVT belgilari', p1:'DVT belgilari', f_pe_alt:'Boshqa tashxis kamroq ehtimol', p2:'Boshqa tashxis kamroq ehtimol', f_pe_hr:'Puls > 100', p3:'Puls > 100', f_pe_immob:'Yotoq rejimi (> 3 kun)', p4:'Yotoq rejimi (> 3 kun)', f_pe_hx:'PE/DVT', p5:'PE/DVT', f_pe_hemop:'Qon tupurish', p6:'Qon tupurish', f_pe_malig:'Onkologiya', p7:'Onkologiya',
  f_confusion:'Ong chalkashligi', c1:'Ong chalkashligi', f_urea:'Mochevina > 7', c2:'Mochevina > 7', f_rr30:'Nafas ≥ 30', c3:'Nafas ≥ 30', f_bp_low:'Qon bosimi < 90/60', c4:'Qon bosimi < 90/60', f_age65:'Yosh ≥ 65', c5:'Yosh ≥ 65',
  ch_c:'C: Yurak yetishmovchiligi (+1)', ch_h:'H: Gipertenziya (+1)', ch_a2:'A: Yosh ≥ 75 (+2)', ch_d:'D: Qandli diabet (+1)', ch_s2:'S: Insult/TIA (+2)', ch_v:'V: Tomir kasalligi (+1)', ch_a1:'A: Yosh 65-74 (+1)', ch_sex:'S: Ayol jinsi (+1)',
  f_bili:'Bilirubin', f_alb:'Albumin', f_pt:'PV / XNN', f_ascites:'Assit', f_enceph:'Ensefalopatiya', cp_b1:'< 34', cp_b2:'34–50', cp_b3:'> 50', cp_a1:'> 35', cp_a2:'28–35', cp_a3:'< 28', cp_p1:'< 1.7', cp_p2:'1.7–2.3', cp_p3:'> 2.3', cp_as2:'O\'rtacha', cp_as3:'Og\'ir', cp_e2:'I–II', cp_e3:'III–IV',
  f_weight:'Vazn (kg)', f_height:'Bo\'y (sm)', f_cr:'Kreatinin', f_age:'Yosh', f_sex:'Jins', sex_m:'Erkak', sex_f:'Ayol',
  f_mews_rr:'Nafas', f_mews_hr:'Puls', f_mews_sbp:'Bosim', f_mews_temp:'Harorat', f_mews_avpu:'Ong darajasi',
  f_cough_a:'Yo\'tal yo\'q', f_exudates:'Karash', f_lymph:'Limfa tugun', f_temp38:'Harorat > 38', f_c_age:'Yosh guruhi', c_age_1:'3–14 yosh (+1)', c_age_2:'15–44 yosh (0)', c_age_3:'≥ 45 yosh (-1)',
  f_nihss_score:'NIHSS bali',
  f_pao2:'PaO2/FiO2', f_plt:'Trombotsitlar', f_bili_sofa:'Bilirubin', f_map:'Bosim/Vazopressor', f_gcs_sofa:'GCS', f_cr_sofa:'Kreatinin / Siydik',
  f_age55:'Yosh > 55', f_wbc:'Leykotsit > 16k', f_glu:'Glyukoza > 200', f_ldh:'LDH > 350', f_ast:'AST > 250', f_hct_drop:'Gematokrit > 10%', f_bun_rise:'Mochevina', f_ca_low:'Kaltsiy < 8', f_pao2_low:'PaO2 < 60', f_base_def:'Asos defitsiti > 4', f_fluid_seq:'Suyuqlik > 6L',
  f_psi_age:'Yosh', psi_age:'Yosh', f_psi_sex:'Jins', psi_sex:'Jins', f_psi_nh:'Qariyalar uyi', psi_nh:'Qariyalar uyi', f_psi_neo:'Onkologiya', psi_neo:'Onkologiya', f_psi_liv:'Jigar', psi_liv:'Jigar', f_psi_chf:'Yurak yetish.', psi_chf:'Yurak yetish.', f_psi_cvd:'Insult', psi_cvd:'Insult', f_psi_ren:'Buyrak', psi_ren:'Buyrak', f_psi_ams:'Ong o\'zgarishi', psi_ams:'Ong o\'zgarishi', f_psi_rr:'Nafas ≥ 30', psi_rr:'Nafas ≥ 30', f_psi_sbp:'Bosim < 90', psi_sbp:'Bosim < 90', f_psi_temp:'Harorat < 35 yoki ≥ 40', psi_temp:'Harorat < 35 yoki ≥ 40', f_psi_pulse:'Puls ≥ 125', psi_pulse:'Puls ≥ 125', f_psi_ph:'pH < 7.35', psi_ph:'pH < 7.35', f_psi_bun:'Mochevina ≥ 30', psi_bun:'Mochevina ≥ 30', f_psi_na:'Natriy < 130', psi_na:'Natriy < 130', f_psi_gluc:'Glyukoza ≥ 250', psi_gluc:'Glyukoza ≥ 250', f_psi_hct:'Gematokrit < 30%', psi_hct:'Gematokrit < 30%', f_psi_pao2:'PaO2 < 60', psi_pao2:'PaO2 < 60', f_psi_eff:'Plevral suyuqlik', psi_eff:'Plevral suyuqlik',

  // NEW NIHSS FULL QUESTIONS (Uzbek)
  n1a_q:'1a. Ong darajasi', n1a_0:'0: Hushyor', n1a_1:'1: Uyg\'otib bo\'ladigan', n1a_2:'2: Sopor', n1a_3:'3: Koma',
  n1b_q:'1b. Savollar (Oy/Yosh)', n1b_0:'0: Ikkalasi to\'g\'ri', n1b_1:'1: Bittasi to\'g\'ri', n1b_2:'2: Ikkalasi noto\'g\'ri',
  n1c_q:'1c. Buyruqlar (Ko\'z, musht)', n1c_0:'0: Ikkalasini bajaradi', n1c_1:'1: Bittasini bajaradi', n1c_2:'2: Bajarmaydi',
  n2_q:'2. Ko\'z harakati', n2_0:'0: Normal', n2_1:'1: Qisman parez', n2_2:'2: Majburiy burilish',
  n3_q:'3. Ko\'rish maydoni', n3_0:'0: Normal', n3_1:'1: Qisman gemianopsiya', n3_2:'2: To\'liq gemianopsiya', n3_3:'3: Ikki tomonlama ko\'rlik',
  n4_q:'4. Yuz parezi', n4_0:'0: Normal', n4_1:'1: Biroz assimetriya', n4_2:'2: Qisman falaj', n4_3:'3: To\'liq falaj',
  n5a_q:'5a. Chap qo\'l', n5a_0:'0: Normal', n5a_1:'1: Tushish (Drift)', n5a_2:'2: Tortishishga qarshi', n5a_3:'3: Tortishishga qarshilik yo\'q', n5a_4:'4: Harakat yo\'q',
  n5b_q:'5b. O\'ng qo\'l', n5b_0:'0: Normal', n5b_1:'1: Tushish (Drift)', n5b_2:'2: Tortishishga qarshi', n5b_3:'3: Tortishishga qarshilik yo\'q', n5b_4:'4: Harakat yo\'q',
  n6a_q:'6a. Chap oyoq', n6a_0:'0: Normal', n6a_1:'1: Tushish (Drift)', n6a_2:'2: Tortishishga qarshi', n6a_3:'3: Tortishishga qarshilik yo\'q', n6a_4:'4: Harakat yo\'q',
  n6b_q:'6b. O\'ng oyoq', n6b_0:'0: Normal', n6b_1:'1: Tushish (Drift)', n6b_2:'2: Tortishishga qarshi', n6b_3:'3: Tortishishga qarshilik yo\'q', n6b_4:'4: Harakat yo\'q',
  n7_q:'7. Ataksiya', n7_0:'0: Yo\'q', n7_1:'1: Bitta a\'zoda', n7_2:'2: Ikkita a\'zoda',
  n8_q:'8. Sezgi', n8_0:'0: Normal', n8_1:'1: Qisman yo\'qotish', n8_2:'2: To\'liq yo\'qotish',
  n9_q:'9. Nutq', n9_0:'0: Afaziya yo\'q', n9_1:'1: Yengil/O\'rtacha', n9_2:'2: Og\'ir afaziya', n9_3:'3: Global/Soqovlik',
  n10_q:'10. Dizartriya', n10_0:'0: Normal', n10_1:'1: Yengil/O\'rtacha', n10_2:'2: Og\'ir',
  n11_q:'11. E\'tiborsizlik', n11_0:'0: Normal', n11_1:'1: Qisman e\'tiborsizlik', n11_2:'2: To\'liq e\'tiborsizlik',

  // --- EXPERT CLINICAL TEXT (Uzbek) ---
  d_gcs: 'Ong darajasini baholash. Jarohatda eng birinchi talab qilinadigan ko\'rsatkich.', r_gcs_mi: 'Yengil bosh jarohati (GCS 13-15).', a_gcs_mi: '• To\'liq nevrologik tekshiruv.<br>• Har 30-60 daqiqada muntazam neyro-kuzatuv.', rx_gcs_mi_n: 'Simptomatik Terapiya', rx_gcs_mi_d: 'Analgeziya (Paratsetamol). Sedativ opioidlar tavsiya etilmaydi.', r_gcs_mo: 'O\'rtacha og\'irlikdagi bosh miya jarohati (GCS 9-12).', a_gcs_mo: '• Zudlik bilan bosh miya KTsi.<br>• Neyrojarrohning shoshilinch konsultatsiyasi.', rx_gcs_mo_n: 'Neyroprotektsiya', rx_gcs_mo_d: 'Levetiratsetam (500 mg v/i) qo\'llashni ko\'rib chiqish.', r_gcs_se: 'Og\'ir bosh jarohati (GCS ≤ 8). Miya dislokatsiyasi xavfi.', a_gcs_se: '• ZUDLIK BILAN nafas yo\'llarini himoyalash (Traxeya intubatsiyasi).<br>• Neyroreanimatsiyaga (ORIT) yotqizish.', rx_gcs_se_n: 'ICP va Sedatsiya', rx_gcs_se_d: 'Induksiya uchun Propofol/Ketamin. Dislokatsiya belgilarida: Mannitol 20%.', gcs_info_title: 'Tahlil: Glazgo shkalasi (GCS)', gcs_info_p1: 'Umumiy ma\'lumot: 1974 yilda ishlab chiqilgan Glazgo Koma Shkalasi bosh miya jarohati va tizimli kasalliklarda ong darajasini standartlashtirilgan tarzda baholaydi.', gcs_info_p2: 'Klinik injular: Harakat balli umumiy prognozning eng ishonchli ko\'rsatkichidir. Agar javoblar assimetrik bo\'lsa, har doim ENG YAXSHI javob beradigan tomonni baholang.', gcs_info_p3: 'Keyingi qadamlar: GCS 8 yoki undan past bo\'lishi koma holatini anglatadi. Bu nafas yo\'llarini mustaqil himoya qila olmaslikni ko\'rsatadi va zudlik bilan intubatsiyani talab qiladi.',
  d_apgar: 'Chaqaloqni 1 va 5-daqiqada baholash. Reanimatsiya taktikasini belgilaydi.', r_apgar_no: 'Normal holat (7-10).', a_apgar_no: '• Doimiy tug\'ruqdan keyingi parvarish.<br>• Ona bilan kontakt.', rx_apgar_no_n: 'Profilaktika', rx_apgar_no_d: 'Vitamin K 1 mg.', r_apgar_mo: 'O\'rtacha asfiksiya (4-6).', a_apgar_mo: '• Taktil stimulyatsiya.<br>• Kislorod berish.', rx_apgar_mo_n: 'Oksigenoterapiya', rx_apgar_mo_d: 'Saturatsiyaga qarab kislorod.', r_apgar_cr: 'Og\'ir asfiksiya (0-3).', a_apgar_cr: '• Zudlik bilan reanimatsiya.<br>• IVL (niqob orqali).', rx_apgar_cr_n: 'Reanimatsiya', rx_apgar_cr_d: 'Puls < 60 bo\'lsa v/i Epinefrin.', apgar_info_title: 'Tahlil: Apgar shkalasi', apgar_info_p1: 'Umumiy ma\'lumot: 1-daqiqadagi ball chaqaloqning tug\'ruq jarayoniga qanday toqat qilganini aks ettiradi, 5-daqiqadagi ball esa ekstrauterin moslashuvni baholaydi.', apgar_info_p2: 'Klinik injular: Yurak urishi va nafas olish omon qolish uchun eng muhimdir, teri rangi (akrotsianoz) esa eng kam ishonchli hisoblanadi.', apgar_info_p3: 'Ko\'rsatmalar: 5-daqiqada ≤ 3 ball nevrologik shikastlanish xavfining oshishi bilan bog\'liq va faol neonatal reanimatsiyani talab qiladi.',
  d_dvt: 'Chuqur vena trombozi (TVT) ehtimolini baholash.', r_dvt_lo: 'TVT ehtimoli past.', a_dvt_lo: '• D-Dimer tekshiruvi.<br>• Manfiy bo\'lsa TVT istisno qilinadi.', rx_dvt_lo_n: 'Antikoagulyantlar kerak emas', rx_dvt_lo_d: 'Empirik terapiya shart emas.', r_dvt_md: 'O\'rtacha xavf.', a_dvt_md: '• D-Dimer musbat bo\'lsa UTT qilinadi.', rx_dvt_md_n: 'Kuzatuv', rx_dvt_md_d: 'UTT 4 soatdan ortiq kechiksa terapiyani boshlash.', r_dvt_hi: 'TVT ehtimoli yuqori.', a_dvt_hi: '• Zudlik bilan oyoq venalari UTTsi.', rx_dvt_hi_n: 'Empirik Terapiya', rx_dvt_hi_d: 'Kechiksa NOAK (Apiksaban) yoki Enoksaparin boshlang.', dvt_info_title: 'Tahlil: Wells TVT', dvt_info_p1: 'Umumiy ma\'lumot: Qimmatbaho vizualizatsiya yoki xavfli antikoagulyatsiyani boshlashdan oldin Chuqur Vena Trombozi ehtimolini taxmin qilish uchun tasdiqlangan qoida.', dvt_info_p2: 'Klinik injular: "Boshqa tashxis ehtimoli" mezoni kuchli klinik fikrlashni talab qiladi. Sellulit, Baker kistasining yorilishi, yoki yurak yetishmovchiligini istisno qiling.', dvt_info_p3: 'Keyingi qadamlar: Yuqori xavfli bemorlarda (≥2) D-dimerning o\'zi yetarli emas; to\'g\'ridan-to\'g\'ri proksimal kompressiyali ultratovush tekshiruviga o\'ting.',
  d_pe: 'O\'pka emboliyasini (O\'ATE) vizualizatsiya qilish ehtimoli.', r_pe_lo: 'O\'ATE ehtimoli past.', a_pe_lo: '• D-Dimer orqali istisno qilish.', rx_pe_lo_n: 'Terapiya kerak emas', rx_pe_lo_d: 'Antikoagulyantlar qarshi ko\'rsatilgan.', r_pe_md: 'O\'rtacha xavf.', a_pe_md: '• Musbat D-Dimer bo\'lsa KT-AG.', rx_pe_md_n: 'Kutish', rx_pe_md_d: 'KT natijasini kuting.', r_pe_hi: 'O\'ATE ehtimoli yuqori.', a_pe_hi: '• Zudlik bilan KT-AG.<br>• Reanimatsiyaga yotqizish.', rx_pe_hi_n: 'Agressiv Terapiya', rx_pe_hi_d: 'Geparin yoki Enoksaparin zudlik bilan boshlanadi.', pe_info_title: 'Tahlil: Wells O\'ATE', pe_info_p1: 'Umumiy ma\'lumot: Keraksiz KT-angiografiya (KTPA) va uning nurlanish/kontrast nefropatiyasi xavfini oldini olish uchun O\'pka Arteriyasi Tromboemboliyasi xavfini baholaydi.', pe_info_p2: 'Klinik injular: Taxikardiya (>100 bpm) kuchli, ammo nospetsifik prediktordir. EKG da S1Q3T3 belgilariga e\'tibor bering.', pe_info_p3: 'Keyingi qadamlar: Agar baho >4 bo\'lsa, D-Dimer testini BUYURMANG; u O\'ATE ni xavfsiz inkor eta olmaydi. Darhol KTPA ga o\'ting va empirik antikoagulyatsiya boshlang.',
  d_curb65: 'Pnevmoniyada (KTP) o\'lim xavfi stratifikatsiyasi.', r_curb_lo: 'O\'lim xavfi past (< 2%).', a_curb_lo: '• Uyda davolanish.<br>• 48 soatdan keyin nazorat.', rx_curb_lo_n: 'Ambulator Antibiotiklar', rx_curb_lo_d: 'Amoksitsillin yoki Doksitsiklin (5-7 kun).', r_curb_md: 'O\'rtacha xavf (~9%).', a_curb_md: '• Terapiya bo\'limiga yotqizish.<br>• Qon va balg\'am ekmasi.', rx_curb_md_n: 'Statsionar Terapiya', rx_curb_md_d: 'Vena ichiga Amoksitsillin/Klavulanat + peroral Klaritromitsin.', r_curb_hi: 'Og\'ir pnevmoniya.', a_curb_hi: '• Majburiy gospitalizatsiya (ORIT).<br>• IVL ga tayyorgarlik.', rx_curb_hi_n: 'Keng Spektrli Terapiya (ORIT)', rx_curb_hi_d: 'V/i Seftriakson 2g + Makrolid. MRSA ni hisobga olish.', curb_info_title: 'Tahlil: CURB-65', curb_info_p1: 'Umumiy ma\'lumot: Britaniya Torakal Jamiyati tomonidan kasalxonadan tashqari pnevmoniyada 30 kunlik o\'lim xavfini aniq bashorat qilish uchun tasdiqlangan.', curb_info_p2: 'Klinik injular: Mochevina > 7 mmol/L sepsisga ikkilamchi bo\'lgan degidratatsiya va yomon buyrak perfuziyasini aks ettiradi. "Ong chalkashligi" AMTS ≤ 8 deb rasman ta\'riflanadi.', curb_info_p3: 'Keyingi qadamlar: 0-1 ball uyda xavfsiz davolanishni anglatadi. 2 ball palataga yotqizishni talab qiladi. 3+ ball og\'ir pnevmoniyani (o\'lim darajasi 40% gacha) bildiradi va ORIT ni talab qiladi.',
  d_chads2: 'Yurak bo\'lmachalari fibrillyatsiyasida insult xavfini baholash.', r_chads_lo: 'Past xavf.', a_chads_lo: '• Turmush tarzini o\'zgartirish.', rx_chads_lo_n: 'Dori kerak emas', rx_chads_lo_d: 'Antitrombotik dori tavsiya etilmaydi.', r_chads_md: 'O\'rtacha xavf.', a_chads_md: '• Qon ketish xavfini hisobga olgan holda davolash.', rx_chads_md_n: 'NOAK tavsiya etiladi', rx_chads_md_d: 'Bemor bilan muhokama qilish.', r_chads_hi: 'Insult xavfi yuqori.', a_chads_hi: '• Tizimli antikoagulyatsiya uchun qat\'iy ko\'rsatma.', rx_chads_hi_n: 'Uzoq muddatli Terapiya', rx_chads_hi_d: 'Apiksaban 5mg yoki Rivaroksaban 20mg.', chads_info_title: 'Tahlil: CHA₂DS₂-VASc', chads_info_p1: 'Umumiy ma\'lumot: AHA/ACC/ESC tomonidan tavsiya etilgan, no-klapanli bo\'lmachalar fibrillyatsiyasi bo\'lgan bemorlarda ishemik insultning yillik xavfini hisoblash tizimi.', chads_info_p2: 'Klinik injular: "No-klapanli" o\'rtacha-og\'ir mitrali stenoz yoki mexanik yurak klapani yo\'qligini anglatadi. Qon ketish xavfini o\'lchash uchun har doim HAS-BLED shkalasini ham hisoblang.', chads_info_p3: 'Ko\'rsatmalar: Erkaklarda ≥2 yoki ayollarda ≥3 ball umrbod peroral antikoagulyatsiya uchun qat\'iy ko\'rsatma bo\'lib, xavfsizlik profili tufayli NOAKlar Varfarindan afzal ko\'riladi.',
  d_cp: 'Jigar sirrozi og\'irligini prognostik tasniflash.', r_cp_a: 'A sinf: Kompensatsiyalangan.', a_cp_a: '• Gepatolog kuzatuvi.<br>• Qizilo\'ngach venalarini tekshirish.', rx_cp_a_n: 'Standart', rx_cp_a_d: 'Gepatotoksik dorilardan saqlaning.', r_cp_b: 'B sinf: O\'rtacha.', a_cp_b: '• Jarrohlik xavfi yuqori.', rx_cp_b_n: 'Maqsadli Davolash', rx_cp_b_d: 'Portal gipertenziya uchun Propranolol.', r_cp_c: 'C sinf: Dekompensatsiyalangan.', a_cp_c: '• Zudlik bilan transplantatsiya markaziga.', rx_cp_c_n: 'Asoratlarni Davolash', rx_cp_c_d: 'Assit uchun Spironolakton. Ensefalopatiya uchun Laktuloza.', cp_info_title: 'Tahlil: Child-Pugh shkalasi', cp_info_p1: 'Umumiy ma\'lumot: Sirroz bilan kasallangan bemorlarda 1 va 2 yillik omon qolishni baholash hamda perioperativ o\'lim xavfini aniqlash uchun klassik prognostik model.', cp_info_p2: 'Klinik injular: Subyektiv mezonlar (assit va ensefalopatiya) so\'nggi tibbiy aralashuvlar (masalan, kuchli diurez yoki laktuloza terapiyasi) tufayli sun\'iy ravishda o\'zgarishi mumkin.', cp_info_p3: 'Keyingi qadamlar: A sinf ~100% 1 yillik omon qolishni ta\'minlaydi. C sinf esa terminal bosqichdagi dekompensatsiyani bildiradi (~45% 1 yillik omon qolish) va jigar transplantatsiyasini talab qiladi.',
  d_bmi: 'JSST klassifikatsiyasi chegaralari bilan tana vazni indeksi (TVI).', r_bmi_un: 'Vazn yetishmovchiligi.', a_bmi_un: '• Diyetolog konsultatsiyasi.', rx_bmi_un_n: 'Qo\'shimcha oziqlanish', rx_bmi_un_d: 'Yuqori kaloriyali parhez.', r_bmi_no: 'Normal vazn.', a_bmi_no: '• Sog\'lom turmush tarzi.', rx_bmi_no_n: 'Profilaktika', rx_bmi_no_d: 'Hech qanday dori kerak emas.', r_bmi_ov: 'Ortiqcha vazn.', a_bmi_ov: '• 5-10% vazn yo\'qotish tavsiya etiladi.', rx_bmi_ov_n: 'Turmush Tarzi', rx_bmi_ov_d: 'Muntazam jismoniy mashqlar.', r_bmi_ob1: 'I darajali semizlik.', a_bmi_ob1: '• Yondosh kasalliklarni tekshirish.', rx_bmi_ob1_n: 'Farmakoterapiya', rx_bmi_ob1_d: 'Semaglutid kabi GLP-1 agonistlari.', r_bmi_ob2: 'II+ darajali semizlik.', a_bmi_ob2: '• Bariatrik jarrohlik konsultatsiyasi.', rx_bmi_ob2_n: 'Jarrohlik', rx_bmi_ob2_d: 'Maksimal tibbiy terapiya qilib ko\'rish.', bmi_info_title: 'Tahlil: Tana Vazni Indeksi (TVI)', bmi_info_p1: 'Umumiy ma\'lumot: Antropometrik kuzatuv uchun Jahon Sog\'liqni Saqlash Tashkiloti (JSST) standarti bo\'lib, kardiovaskulyar va metabolik xavf uchun asosiy o\'lchovni beradi.', bmi_info_p2: 'Klinik injular: TVI mushak massasi va yog\' to\'qimasini farqlamaydi. Shuningdek, u "normal vaznli semizlik"dagi xavfli visseral yog\'lanishni aniqlay olmasligi mumkin.', bmi_info_p3: 'Keyingi qadamlar: Osiyo populyatsiyalarida pastroq TVI darajalarida ham kardiometabolik xavflar yuqori bo\'ladi; JSST qoidalariga ko\'ra ularda "Ortiqcha vazn" ≥23 dan va "Semizlik" ≥25 dan boshlanadi.',
  d_egfr: 'CKD-EPI 2021 tenglamasi orqali buyrak faoliyatini baholash.', r_egfr_no: 'Normal eGFR (≥ 60).', a_egfr_no: '• Muntazam monitoring.', rx_egfr_no_n: 'Standart', rx_egfr_no_d: 'Proteinuriya bo\'lsa AAF inhibitori.', r_egfr_md: 'O\'rtacha SBK (30 - 59).', a_egfr_md: '• Dori dozalarini kamaytirish.', rx_egfr_md_n: 'Dozalarni to\'g\'rilash', rx_egfr_md_d: 'Metformin va NOAK dozasini pasaytirish.', r_egfr_se: 'Og\'ir SBK (< 30).', a_egfr_se: '• Nefrologga yuborish.<br>• Dializga tayyorgarlik.', rx_egfr_se_n: 'Nefro-himoya', rx_egfr_se_d: 'Metforminni to\'xtatish. Kaliy nazorati.', egfr_info_title: 'Tahlil: eGFR (CKD-EPI)', egfr_info_p1: 'Umumiy ma\'lumot: 2021 yilgi CKD-EPI tenglamasi bahsli irqiy koeffitsientni olib tashlab, haqiqiy Glomerulyar Filtratsiya Tezligini eng aniq aks ettiradi.', egfr_info_p2: 'Klinik injular: O\'tkir buyrak shikastlanishida (kreatinin barqaror bo\'lmaganda), amputatsiyaga uchragan bemorlarda, og\'ir to\'yib ovqatlanmaslik yoki ekstremal mushak massasida eGFR formulalari noaniq bo\'ladi.', egfr_info_p3: 'Ko\'rsatmalar: 3 oydan ko\'proq vaqt davomida eGFR <60 ml/min bo\'lishi Surunkali Buyrak Kasalligini (SBK) tasdiqlaydi. Buyrak orqali chiqadigan dorilarni yozishdan oldin eGFR ni tekshirish majburiydir.',
  d_mews: 'Klinik yomonlashuvni erta aniqlash uchun fiziologiyani kuzating.', r_mews_lo: 'Fiziologik stabil.', a_mews_lo: '• Har 4-6 soatda kuzatuv.', rx_mews_lo_n: 'Eskalatsiya yo\'q', rx_mews_lo_d: 'Amaldagi dorilar davom ettiriladi.', r_mews_md: 'Ehtimoliy beqarorlik.', a_mews_md: '• 30 minut ichida shifokor ko\'rigi.', rx_mews_md_n: 'Maqsadli yordam', rx_mews_md_d: 'Kislorod berish. Gipotenziyada suyuqlik.', r_mews_hi: 'Kritik yomonlashuv.', a_mews_hi: '• Zudlik bilan reanimatsiya chaqirish.', rx_mews_hi_n: 'Tayyorgarlik', rx_mews_hi_d: 'Intubatsiya va vazopressorlarga tayyor bo\'lish.', mews_info_title: 'Tahlil: MEWS shkalasi', mews_info_p1: 'Umumiy ma\'lumot: Yurak to\'xtashidan bir necha soat oldin halokatli klinik yomonlashuv xavfi ostida bo\'lgan bemorlarni aniqlash uchun barcha joyda qo\'llaniladigan shkala.', mews_info_p2: 'Klinik injular: Taxipnoe (nafas tezlashishi) yuqori sezuvchanlikka ega va ko\'pincha tizimli stress yoki metabolik atsidozning eng birinchi ko\'rsatkichidir. Harorat yolg\'iz o\'zi eng kam prognoz ahamiyatiga ega.', mews_info_p3: 'Keyingi qadamlar: ≥5 ball zudlik bilan Tibbiy Tez Yordam Jamoasi (RRT) ni chaqirishni talab qiladi va ORIT ga o\'tkazish ehtimoli yuqori ekanligini bildiradi.',
  d_centor: 'A guruhi streptokokk faringiti ehtimolini klinik baholash.', r_centor_lo: 'Strep ehtimoli past (Virusli).', a_centor_lo: '• Tomoqdan surtma shart emas.', rx_centor_lo_n: 'Simptomatik Davolash', rx_centor_lo_d: 'Ibuprofen. Antibiotik BERILMAYDI.', r_centor_md: 'Strep mumkin.', a_centor_md: '• Ekspress-test qilish.', rx_centor_md_n: 'Kutish', rx_centor_md_d: 'Test musbat bo\'lsa antibiotik berish.', r_centor_hi: 'Strep ehtimoli yuqori.', a_centor_hi: '• Empirik antibiotiklar boshlash mumkin.', rx_centor_hi_n: 'Antibiotikoterapiya', rx_centor_hi_d: 'Penitsillin V yoki Amoksitsillin 10 kun.', centor_info_title: 'Tahlil: Centor mezonlari', centor_info_p1: 'Umumiy ma\'lumot: O\'zgartirilgan Centor qoidasi faringitning A guruhi beta-gemolitik Streptokokk (GAS) tomonidan kelib chiqish ehtimolini hisoblaydi.', centor_info_p2: 'Klinik injular: Uning asosiy kuchi manfiy prognoz qiymatidadir — ya\'ni, Streptokokkni INKOR ETISH va keraksiz antibiotiklarni oldini olish uchun xizmat qiladi. 3 yoshgacha bo\'lgan bolalarda tasdiqlanmagan.', centor_info_p3: 'Ko\'rsatmalar: 0-1 ball: test va antibiotiklar kerak emas. 2-3 ball: Ekspress Strep Testini o\'tkazing. 4-5 ball: Revmatik isitmani oldini olish uchun empirik Amoksitsillin asosli.',
  d_nihss: 'Trombolizisni qo\'llash uchun insult og\'irligini miqdoriy baholash.', r_nihss_mi: 'Yengil insult.', a_nihss_mi: '• Insult bo\'limiga yotqizish.', rx_nihss_mi_n: 'Antiagregant', rx_nihss_mi_d: 'Aspirin 300 mg.', r_nihss_mo: 'O\'rtacha insult.', a_nihss_mo: '• IV Trombolizisga ko\'rsatma.', rx_nihss_mo_n: 'Reperfuziya', rx_nihss_mo_d: 'Agar < 4.5 soat o\'tgan bo\'lsa Alteplaza.', r_nihss_ms: 'O\'rta-og\'ir insult.', a_nihss_ms: '• Trombektomiya jamoasini chaqirish.', rx_nihss_ms_n: 'Qo\'shma Terapiya', rx_nihss_ms_d: 'Trombolizis va Trombektomiya.', r_nihss_se: 'Og\'ir insult.', a_nihss_se: '• Miya shishi va gemorragik transformatsiya xavfi.', rx_nihss_se_n: 'ORIT', rx_nihss_se_d: 'Qon bosimini qat\'iy nazorat qilish.', nihss_info_title: 'Tahlil: NIHSS shkalasi', nihss_info_p1: 'Umumiy ma\'lumot: O\'tkir insult bilan bog\'liq nevrologik defitsitning og\'irligini tezkor baholash uchun xalqaro "oltin standart" (15 banddan iborat).', nihss_info_p2: 'Klinik injular: Shkala asosan oldingi qon aylanish havzasi (SMA) insultlariga moyil. Miya ustuni yoki miyachadagi (orqa) insultlarda ballar sun\'iy ravishda past chiqishi mumkin.', nihss_info_p3: 'Keyingi qadamlar: Tez yordam, Qabul bo\'limi va Nevrologiya o\'rtasidagi aloqani standartlashtiradi. IV Alteplaza (tPA) va Endovaskulyar Trombektomiya (EVT) uchun yaroqlilikni aniqlashda muhim ahamiyatga ega.',
  d_sofa: 'A\'zolar yetishmovchiligini baholash orqali sepsisni aniqlash (Sepsis-3).', r_sofa_lo: 'Past xavf.', a_sofa_lo: '• Infeksiya o\'chog\'ini topish.', rx_sofa_lo_n: 'Antibiotiklar', rx_sofa_lo_d: 'Gumon qilingan manbaga qarab tayinlash.', r_sofa_md: 'A\'zolar disfunksiyasi (Sepsis).', a_sofa_md: '• Sepsis-3 tashxisi tasdiqlandi.', rx_sofa_md_n: 'Reanimatsiya', rx_sofa_md_d: 'Keng spektrli v/i antibiotiklar. Suyuqlik.', r_sofa_hi: 'Septik Shok.', a_sofa_hi: '• Zudlik bilan ORIT.<br>• Markaziy vena kateteri.', rx_sofa_hi_n: 'Vazopressorlar', rx_sofa_hi_d: 'Norepinefrin (Maqsadli MAP > 65).', sofa_info_title: 'Tahlil: SOFA shkalasi', sofa_info_p1: 'Umumiy ma\'lumot: Sepsis-3 diagnostika mezonlarining asosi bo\'lib, ORIT dagi o\'lim va poliorgan yetishmovchiligi darajasini kuzatib boradi.', sofa_info_p2: 'Klinik injular: Tezkor qSOFA dan farqli o\'laroq, to\'liq SOFA shkalasi a\'zolar disfunksiyasini ob\'ektivlashtirish uchun keng qamrovli laboratoriya ma\'lumotlarini (Trombotsitlar, Bilirubin, Kreatinin, ABG) talab qiladi.', sofa_info_p3: 'Ko\'rsatmalar: SOFA balining bazaviy darajadan ≥ 2 ballga o\'tkir ko\'tarilishi Sepsisning klinik tashxisini rasmiy ravishda tasdiqlaydi (minimal 10% o\'lim xavfi bilan).',
  d_ranson: 'O\'tkir pankreatitda o\'lim xavfini bashorat qilish algoritmi.', r_ranson_lo: 'Yengil pankreatit.', a_ranson_lo: '• Umumiy bo\'limga yotqizish.', rx_ranson_lo_n: 'Simptomatik Terapiya', rx_ranson_lo_d: 'Suyuqliklar va Og\'riq qoldiruvchilar (Opioidlar).', r_ranson_md: 'O\'rtacha-og\'ir pankreatit.', a_ranson_md: '• Agressiv infuzion terapiya.', rx_ranson_md_n: 'Agressiv Infuziya', rx_ranson_md_d: 'Ringer laktat yoki Hartman (250-500 ml/soat).', r_ranson_hi: 'Og\'ir pankreatit.', a_ranson_hi: '• Majburiy ORIT.<br>• Jarroh konsultatsiyasi.', rx_ranson_hi_n: 'ORIT', rx_ranson_hi_d: 'Antibiotiklar faqat nekroz infeksiyalansa.', ranson_info_title: 'Tahlil: Ranson mezonlari', ranson_info_p1: 'Umumiy ma\'lumot: Yallig\'lanish va metabolik markerlar asosida o\'tkir pankreatitda o\'lim va og\'irlik darajasini taxmin qilish uchun 1974 yildagi original prognostik model.', ranson_info_p2: 'Klinik injular: Baholash to\'liq 48 soatni talab qiladi. Massiv suyuqlik sekvestratsiyasi (>6L) va gipokalsemiya kabi markerlar kuchli retroperitoneal nekrozni aks ettiradi.', ranson_info_p3: 'Keyingi qadamlar: ≥3 ball og\'ir o\'tkir pankreatitni anglatadi. Zamonaviy amaliyot ORIT da kunlik dinamik kuzatuv uchun Ransonni ko\'pincha APACHE II yoki BISAP bilan birlashtiradi.',
  d_psi: 'Kasalxonadan tashqari pnevmoniya uchun keng qamrovli o\'lim xavfi stratifikatsiyasi.', r_psi_1: 'I Sinf (Past xavf).', a_psi_1: '• Uyda davolanish.', rx_psi_1_n: 'Peroral Antibiotik', rx_psi_1_d: 'Makrolid yoki Doksitsiklin.', r_psi_2: 'II Sinf (Past xavf).', a_psi_2: '• Uyda davolanish.', rx_psi_2_n: 'Peroral Antibiotik', rx_psi_2_d: 'Amoksitsillin yoki Makrolid.', r_psi_3: 'III Sinf (O\'rtacha).', a_psi_3: '• Qisqa muddatli kasalxonada kuzatuv.', rx_psi_3_n: 'Qisqa muddatli V/I', rx_psi_3_d: 'Ftorxinolon yoki Beta-laktam + Makrolid.', r_psi_4: 'IV Sinf (Yuqori xavf).', a_psi_4: '• Kasalxonaga yotqizish.', rx_psi_4_n: 'Vena ichiga Agressiv Terapiya', rx_psi_4_d: 'Seftriakson + Azitromitsin.', r_psi_5: 'V Sinf (Juda Yuqori).', a_psi_5: '• Zudlik bilan Reanimatsiya (ORIT).', rx_psi_5_n: 'Keng Spektrli (ORIT)', rx_psi_5_d: 'Beta-laktam + Makrolid. MRSA ni yopish.', psi_info_title: 'Tahlil: PSI/PORT shkalasi', psi_info_p1: 'Umumiy ma\'lumot: Kasalxonadan tashqari pnevmoniya bilan kasallangan bemorlar uchun 30 kunlik o\'lim ehtimolini hisoblash uchun yoshga qarab moslashtirilgan klinik qoida.', psi_info_p2: 'Klinik injular: Garchi u CURB-65 dan ko\'ra ancha murakkabroq bo\'lsa ham (20 ta o\'zgaruvchini talab qiladi), PSI statistik jihatdan past xavfli bemorlarni uyga javob berish uchun aniqlashda ustunroqdir.', psi_info_p3: 'Ko\'rsatmalar: I va II sinflarni xavfsiz ravishda uyga javob berish mumkin. III sinf klinik kuzatuvni talab qiladi. IV va V sinflar mutlaqo kasalxonaga yotqizishni (ko\'pincha ORIT) talab qiladi.'
}
};

window.t = function(key) {
    var lang = localStorage.getItem('wardcalc_lang') || 'en';
    var dict = (window.T && window.T[lang]) ? window.T[lang] : (window.T ? window.T.en : {});
    return dict[key] || (window.T && window.T.en ? window.T.en[key] : key) || key;
};
